/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContentCreateRequest,
  ContentSearchRequest,
  ResultDTOContentDetail,
  ResultDTOListChannelDto,
  ResultDTOResInfinityListContentListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
  UploadBody,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 콘텐츠 상세
 */
export const detail1 = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "GET",
    signal,
  });
};

export const getDetail1QueryKey = (id?: number) => {
  return [`/v1/content/${id}`] as const;
};

export const getDetail1QueryOptions = <
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetail1QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail1>>> = ({
    signal,
  }) => detail1(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Detail1QueryResult = NonNullable<
  Awaited<ReturnType<typeof detail1>>
>;
export type Detail1QueryError = unknown;

export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail1>>,
          TError,
          Awaited<ReturnType<typeof detail1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail1>>,
          TError,
          Awaited<ReturnType<typeof detail1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 콘텐츠 상세
 */

export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetail1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 콘텐츠 수정
 */
export const update1 = (
  id: number,
  contentCreateRequest: ContentCreateRequest
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
  });
};

export const getUpdate1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update1>>,
    TError,
    { id: number; data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["update1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update1>>,
    { id: number; data: ContentCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update1(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update1MutationResult = NonNullable<
  Awaited<ReturnType<typeof update1>>
>;
export type Update1MutationBody = ContentCreateRequest;
export type Update1MutationError = unknown;

/**
 * @summary 콘텐츠 수정
 */
export const useUpdate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update1>>,
      TError,
      { id: number; data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getUpdate1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 삭제
 */
export const _delete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/content/${id}`,
    method: "DELETE",
  });
};

export const getDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["_delete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return _delete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof _delete>>
>;

export type _DeleteMutationError = unknown;

/**
 * @summary 콘텐츠 삭제
 */
export const useDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 등록
 */
export const create = (
  contentCreateRequest: ContentCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
    signal,
  });
};

export const getCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: ContentCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof create>>
>;
export type CreateMutationBody = ContentCreateRequest;
export type CreateMutationError = unknown;

/**
 * @summary 콘텐츠 등록
 */
export const useCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 썸네일/파일을 스토리지(MinIO·S3)에 업로드하고 key/url을 반환한다.
 * @summary 파일 업로드
 */
export const upload = (uploadBody: UploadBody, signal?: AbortSignal) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/content/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: uploadBody,
    signal,
  });
};

export const getUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload>>,
    TError,
    { data: UploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  const mutationKey = ["upload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload>>,
    { data: UploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return upload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof upload>>
>;
export type UploadMutationBody = UploadBody;
export type UploadMutationError = unknown;

/**
 * @summary 파일 업로드
 */
export const useUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload>>,
      TError,
      { data: UploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  const mutationOptions = getUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 콘텐츠 목록.
 * @summary 콘텐츠 목록
 */
export const list1 = (
  contentSearchRequest: ContentSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/v1/content/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentSearchRequest,
    signal,
  });
};

export const getList1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list1>>,
    TError,
    { data: ContentSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list1>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationKey = ["list1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list1>>,
    { data: ContentSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List1MutationResult = NonNullable<
  Awaited<ReturnType<typeof list1>>
>;
export type List1MutationBody = ContentSearchRequest;
export type List1MutationError = unknown;

/**
 * @summary 콘텐츠 목록
 */
export const useList1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list1>>,
      TError,
      { data: ContentSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list1>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationOptions = getList1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 콘텐츠 등록 폼의 채널 선택용.
 * @summary 채널 목록
 */
export const channels = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChannelDto>({
    url: `/v1/content/channels`,
    method: "GET",
    signal,
  });
};

export const getChannelsQueryKey = () => {
  return [`/v1/content/channels`] as const;
};

export const getChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChannelsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof channels>>> = ({
    signal,
  }) => channels(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof channels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof channels>>
>;
export type ChannelsQueryError = unknown;

export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof channels>>,
          TError,
          Awaited<ReturnType<typeof channels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof channels>>,
          TError,
          Awaited<ReturnType<typeof channels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 목록
 */

export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChannelsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
