/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContentCreateRequest,
  ContentSearchRequest,
  ResultDTOContentDetail,
  ResultDTOListChannelDto,
  ResultDTOResInfinityListContentListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
  Upload1Body,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 콘텐츠 상세
 */
export const detail3 = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "GET",
    signal,
  });
};

export const getDetail3QueryKey = (id?: number) => {
  return [`/v1/content/${id}`] as const;
};

export const getDetail3QueryOptions = <
  TData = Awaited<ReturnType<typeof detail3>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetail3QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail3>>> = ({
    signal,
  }) => detail3(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Detail3QueryResult = NonNullable<
  Awaited<ReturnType<typeof detail3>>
>;
export type Detail3QueryError = unknown;

export function useDetail3<
  TData = Awaited<ReturnType<typeof detail3>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail3>>,
          TError,
          Awaited<ReturnType<typeof detail3>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail3<
  TData = Awaited<ReturnType<typeof detail3>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail3>>,
          TError,
          Awaited<ReturnType<typeof detail3>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail3<
  TData = Awaited<ReturnType<typeof detail3>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 콘텐츠 상세
 */

export function useDetail3<
  TData = Awaited<ReturnType<typeof detail3>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail3>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetail3QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 콘텐츠 수정
 */
export const update3 = (
  id: number,
  contentCreateRequest: ContentCreateRequest
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
  });
};

export const getUpdate3MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update3>>,
    TError,
    { id: number; data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update3>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["update3"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update3>>,
    { id: number; data: ContentCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update3(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update3MutationResult = NonNullable<
  Awaited<ReturnType<typeof update3>>
>;
export type Update3MutationBody = ContentCreateRequest;
export type Update3MutationError = unknown;

/**
 * @summary 콘텐츠 수정
 */
export const useUpdate3 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update3>>,
      TError,
      { id: number; data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof update3>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getUpdate3MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 삭제
 */
export const delete2 = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/content/${id}`,
    method: "DELETE",
  });
};

export const getDelete2MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete2>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete2>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["delete2"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete2>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return delete2(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete2MutationResult = NonNullable<
  Awaited<ReturnType<typeof delete2>>
>;

export type Delete2MutationError = unknown;

/**
 * @summary 콘텐츠 삭제
 */
export const useDelete2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete2>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof delete2>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDelete2MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 등록
 */
export const create2 = (
  contentCreateRequest: ContentCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
    signal,
  });
};

export const getCreate2MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create2>>,
    TError,
    { data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["create2"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create2>>,
    { data: ContentCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create2(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create2MutationResult = NonNullable<
  Awaited<ReturnType<typeof create2>>
>;
export type Create2MutationBody = ContentCreateRequest;
export type Create2MutationError = unknown;

/**
 * @summary 콘텐츠 등록
 */
export const useCreate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create2>>,
      TError,
      { data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof create2>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getCreate2MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 썸네일/파일을 스토리지(MinIO·S3)에 업로드하고 key/url을 반환한다.
 * @summary 파일 업로드
 */
export const upload1 = (upload1Body: Upload1Body, signal?: AbortSignal) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/content/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: upload1Body,
    signal,
  });
};

export const getUpload1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload1>>,
    TError,
    { data: Upload1Body },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload1>>,
  TError,
  { data: Upload1Body },
  TContext
> => {
  const mutationKey = ["upload1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload1>>,
    { data: Upload1Body }
  > = (props) => {
    const { data } = props ?? {};

    return upload1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Upload1MutationResult = NonNullable<
  Awaited<ReturnType<typeof upload1>>
>;
export type Upload1MutationBody = Upload1Body;
export type Upload1MutationError = unknown;

/**
 * @summary 파일 업로드
 */
export const useUpload1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload1>>,
      TError,
      { data: Upload1Body },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof upload1>>,
  TError,
  { data: Upload1Body },
  TContext
> => {
  const mutationOptions = getUpload1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 콘텐츠 목록.
 * @summary 콘텐츠 목록
 */
export const list6 = (
  contentSearchRequest: ContentSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/v1/content/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentSearchRequest,
    signal,
  });
};

export const getList6MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list6>>,
    TError,
    { data: ContentSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list6>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationKey = ["list6"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list6>>,
    { data: ContentSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list6(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List6MutationResult = NonNullable<
  Awaited<ReturnType<typeof list6>>
>;
export type List6MutationBody = ContentSearchRequest;
export type List6MutationError = unknown;

/**
 * @summary 콘텐츠 목록
 */
export const useList6 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list6>>,
      TError,
      { data: ContentSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list6>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationOptions = getList6MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 콘텐츠 등록 폼의 채널 선택용.
 * @summary 채널 목록
 */
export const channels = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChannelDto>({
    url: `/v1/content/channels`,
    method: "GET",
    signal,
  });
};

export const getChannelsQueryKey = () => {
  return [`/v1/content/channels`] as const;
};

export const getChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChannelsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof channels>>> = ({
    signal,
  }) => channels(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof channels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof channels>>
>;
export type ChannelsQueryError = unknown;

export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof channels>>,
          TError,
          Awaited<ReturnType<typeof channels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof channels>>,
          TError,
          Awaited<ReturnType<typeof channels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 목록
 */

export function useChannels<
  TData = Awaited<ReturnType<typeof channels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof channels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChannelsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
