/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContentCreateRequest,
  ContentSearchRequest,
  ContentUploadBody,
  ResultDTOContentDetail,
  ResultDTOListChannelDto,
  ResultDTOResInfinityListContentListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 콘텐츠 상세
 */
export const contentDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "GET",
    signal,
  });
};

export const getContentDetailQueryKey = (id?: number) => {
  return [`/v1/content/${id}`] as const;
};

export const getContentDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentDetail>>> = ({
    signal,
  }) => contentDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof contentDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentDetail>>
>;
export type ContentDetailQueryError = unknown;

export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentDetail>>,
          TError,
          Awaited<ReturnType<typeof contentDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentDetail>>,
          TError,
          Awaited<ReturnType<typeof contentDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 콘텐츠 상세
 */

export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContentDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 콘텐츠 수정
 */
export const contentUpdate = (
  id: number,
  contentCreateRequest: ContentCreateRequest
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
  });
};

export const getContentUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentUpdate>>,
    TError,
    { id: number; data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentUpdate>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["contentUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentUpdate>>,
    { id: number; data: ContentCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return contentUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentUpdate>>
>;
export type ContentUpdateMutationBody = ContentCreateRequest;
export type ContentUpdateMutationError = unknown;

/**
 * @summary 콘텐츠 수정
 */
export const useContentUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentUpdate>>,
      TError,
      { id: number; data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentUpdate>>,
  TError,
  { id: number; data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getContentUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 삭제
 */
export const contentDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/content/${id}`,
    method: "DELETE",
  });
};

export const getContentDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["contentDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return contentDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentDelete>>
>;

export type ContentDeleteMutationError = unknown;

/**
 * @summary 콘텐츠 삭제
 */
export const useContentDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContentDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 콘텐츠 등록
 */
export const contentCreate = (
  contentCreateRequest: ContentCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/v1/content`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentCreateRequest,
    signal,
  });
};

export const getContentCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentCreate>>,
    TError,
    { data: ContentCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentCreate>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationKey = ["contentCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentCreate>>,
    { data: ContentCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return contentCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentCreate>>
>;
export type ContentCreateMutationBody = ContentCreateRequest;
export type ContentCreateMutationError = unknown;

/**
 * @summary 콘텐츠 등록
 */
export const useContentCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentCreate>>,
      TError,
      { data: ContentCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentCreate>>,
  TError,
  { data: ContentCreateRequest },
  TContext
> => {
  const mutationOptions = getContentCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 썸네일/파일을 스토리지(MinIO·S3)에 업로드하고 key/url을 반환한다.
 * @summary 파일 업로드
 */
export const contentUpload = (
  contentUploadBody: ContentUploadBody,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/content/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentUploadBody,
    signal,
  });
};

export const getContentUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentUpload>>,
    TError,
    { data: ContentUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentUpload>>,
  TError,
  { data: ContentUploadBody },
  TContext
> => {
  const mutationKey = ["contentUpload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentUpload>>,
    { data: ContentUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return contentUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentUpload>>
>;
export type ContentUploadMutationBody = ContentUploadBody;
export type ContentUploadMutationError = unknown;

/**
 * @summary 파일 업로드
 */
export const useContentUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentUpload>>,
      TError,
      { data: ContentUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentUpload>>,
  TError,
  { data: ContentUploadBody },
  TContext
> => {
  const mutationOptions = getContentUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 콘텐츠 목록. CHURCH_MANAGER는 자기 교회로 스코핑.
 * @summary 콘텐츠 목록
 */
export const contentList = (
  contentSearchRequest: ContentSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/v1/content/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: contentSearchRequest,
    signal,
  });
};

export const getContentListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentList>>,
    TError,
    { data: ContentSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentList>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationKey = ["contentList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentList>>,
    { data: ContentSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return contentList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentListMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentList>>
>;
export type ContentListMutationBody = ContentSearchRequest;
export type ContentListMutationError = unknown;

/**
 * @summary 콘텐츠 목록
 */
export const useContentList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentList>>,
      TError,
      { data: ContentSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentList>>,
  TError,
  { data: ContentSearchRequest },
  TContext
> => {
  const mutationOptions = getContentListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 콘텐츠 등록 폼의 채널 선택용. CHURCH_MANAGER는 자기 교회 채널만.
 * @summary 채널 목록
 */
export const contentChannels = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChannelDto>({
    url: `/v1/content/channels`,
    method: "GET",
    signal,
  });
};

export const getContentChannelsQueryKey = () => {
  return [`/v1/content/channels`] as const;
};

export const getContentChannelsQueryOptions = <
  TData = Awaited<ReturnType<typeof contentChannels>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof contentChannels>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentChannelsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentChannels>>> = ({
    signal,
  }) => contentChannels(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentChannels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentChannelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentChannels>>
>;
export type ContentChannelsQueryError = unknown;

export function useContentChannels<
  TData = Awaited<ReturnType<typeof contentChannels>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentChannels>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentChannels>>,
          TError,
          Awaited<ReturnType<typeof contentChannels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentChannels<
  TData = Awaited<ReturnType<typeof contentChannels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentChannels>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentChannels>>,
          TError,
          Awaited<ReturnType<typeof contentChannels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentChannels<
  TData = Awaited<ReturnType<typeof contentChannels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentChannels>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 채널 목록
 */

export function useContentChannels<
  TData = Awaited<ReturnType<typeof contentChannels>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentChannels>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContentChannelsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
