/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PayApproveCommand,
  PayCancelCommand,
  PayRequestCommand,
  PaymentSearchRequest,
  ResultDTOPaymentReceiptDto,
  ResultDTOPaymentResultDto,
  ResultDTOResInfinityListPaymentListItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 주문에 대해 (가짜) 결제를 요청하고 거래번호를 발급한다.
 * @summary 결제 요청
 */
export const paymentRequestCreate = (
  payRequestCommand: PayRequestCommand,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPaymentResultDto>({
    url: `/v1/payment/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: payRequestCommand,
    signal,
  });
};

export const getPaymentRequestCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentRequestCreate>>,
    TError,
    { data: PayRequestCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentRequestCreate>>,
  TError,
  { data: PayRequestCommand },
  TContext
> => {
  const mutationKey = ["paymentRequestCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentRequestCreate>>,
    { data: PayRequestCommand }
  > = (props) => {
    const { data } = props ?? {};

    return paymentRequestCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentRequestCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentRequestCreate>>
>;
export type PaymentRequestCreateMutationBody = PayRequestCommand;
export type PaymentRequestCreateMutationError = unknown;

/**
 * @summary 결제 요청
 */
export const usePaymentRequestCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof paymentRequestCreate>>,
      TError,
      { data: PayRequestCommand },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof paymentRequestCreate>>,
  TError,
  { data: PayRequestCommand },
  TContext
> => {
  const mutationOptions = getPaymentRequestCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 승인된 결제를 PG에 취소 요청한 뒤(실 PG 연동 시 실제 환불), 주문을 CANCEL/RETURN으로 전이하고 재고 복원 + 환불(REFUND) 영수증을 발급한다. PG 취소를 먼저 호출해 실패 시 내부 원장 반전이 일어나지 않는다.
 * @summary 결제 취소/환불
 */
export const paymentRefundCreate = (
  payCancelCommand: PayCancelCommand,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPaymentResultDto>({
    url: `/v1/payment/refund`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: payCancelCommand,
    signal,
  });
};

export const getPaymentRefundCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentRefundCreate>>,
    TError,
    { data: PayCancelCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentRefundCreate>>,
  TError,
  { data: PayCancelCommand },
  TContext
> => {
  const mutationKey = ["paymentRefundCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentRefundCreate>>,
    { data: PayCancelCommand }
  > = (props) => {
    const { data } = props ?? {};

    return paymentRefundCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentRefundCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentRefundCreate>>
>;
export type PaymentRefundCreateMutationBody = PayCancelCommand;
export type PaymentRefundCreateMutationError = unknown;

/**
 * @summary 결제 취소/환불
 */
export const usePaymentRefundCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof paymentRefundCreate>>,
      TError,
      { data: PayCancelCommand },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof paymentRefundCreate>>,
  TError,
  { data: PayCancelCommand },
  TContext
> => {
  const mutationOptions = getPaymentRefundCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 결제/환불 영수증(ORDER_RECEIPT)을 주문·회원과 조인해 검색/기간 필터 + 페이지네이션으로 반환한다.
 * @summary 결제 내역 목록
 */
export const paymentList = (
  paymentSearchRequest: PaymentSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListPaymentListItem>({
    url: `/v1/payment/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: paymentSearchRequest,
    signal,
  });
};

export const getPaymentListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentList>>,
    TError,
    { data: PaymentSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentList>>,
  TError,
  { data: PaymentSearchRequest },
  TContext
> => {
  const mutationKey = ["paymentList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentList>>,
    { data: PaymentSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return paymentList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentListMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentList>>
>;
export type PaymentListMutationBody = PaymentSearchRequest;
export type PaymentListMutationError = unknown;

/**
 * @summary 결제 내역 목록
 */
export const usePaymentList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof paymentList>>,
      TError,
      { data: PaymentSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof paymentList>>,
  TError,
  { data: PaymentSearchRequest },
  TContext
> => {
  const mutationOptions = getPaymentListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 요청된 결제를 (가짜) 승인하고 주문을 PAID로 전이 + 영수증을 발급한다.
 * @summary 결제 승인
 */
export const paymentApprove = (
  payApproveCommand: PayApproveCommand,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPaymentResultDto>({
    url: `/v1/payment/approve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: payApproveCommand,
    signal,
  });
};

export const getPaymentApproveMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentApprove>>,
    TError,
    { data: PayApproveCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentApprove>>,
  TError,
  { data: PayApproveCommand },
  TContext
> => {
  const mutationKey = ["paymentApprove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentApprove>>,
    { data: PayApproveCommand }
  > = (props) => {
    const { data } = props ?? {};

    return paymentApprove(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentApprove>>
>;
export type PaymentApproveMutationBody = PayApproveCommand;
export type PaymentApproveMutationError = unknown;

/**
 * @summary 결제 승인
 */
export const usePaymentApprove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof paymentApprove>>,
      TError,
      { data: PayApproveCommand },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof paymentApprove>>,
  TError,
  { data: PayApproveCommand },
  TContext
> => {
  const mutationOptions = getPaymentApproveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 주문의 최신 결제(PAY) 영수증을 반환한다.
 * @summary 결제 영수증
 */
export const paymentReceipt = (orderId: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPaymentReceiptDto>({
    url: `/v1/payment/${orderId}/receipt`,
    method: "GET",
    signal,
  });
};

export const getPaymentReceiptQueryKey = (orderId?: number) => {
  return [`/v1/payment/${orderId}/receipt`] as const;
};

export const getPaymentReceiptQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentReceipt>>,
  TError = unknown
>(
  orderId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentReceipt>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentReceiptQueryKey(orderId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentReceipt>>> = ({
    signal,
  }) => paymentReceipt(orderId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orderId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentReceipt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentReceiptQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentReceipt>>
>;
export type PaymentReceiptQueryError = unknown;

export function usePaymentReceipt<
  TData = Awaited<ReturnType<typeof paymentReceipt>>,
  TError = unknown
>(
  orderId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentReceipt>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentReceipt>>,
          TError,
          Awaited<ReturnType<typeof paymentReceipt>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentReceipt<
  TData = Awaited<ReturnType<typeof paymentReceipt>>,
  TError = unknown
>(
  orderId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentReceipt>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentReceipt>>,
          TError,
          Awaited<ReturnType<typeof paymentReceipt>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentReceipt<
  TData = Awaited<ReturnType<typeof paymentReceipt>>,
  TError = unknown
>(
  orderId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentReceipt>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 결제 영수증
 */

export function usePaymentReceipt<
  TData = Awaited<ReturnType<typeof paymentReceipt>>,
  TError = unknown
>(
  orderId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentReceipt>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPaymentReceiptQueryOptions(orderId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
