/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
export type SubscriptionStatusRequestStatus =
  (typeof SubscriptionStatusRequestStatus)[keyof typeof SubscriptionStatusRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionStatusRequestStatus = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  CANCELED: "CANCELED",
} as const;

export interface SubscriptionStatusRequest {
  status: SubscriptionStatusRequestStatus;
}

export interface ResultDTOSubscriptionDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: SubscriptionDetail;
}

export type SubscriptionDetailPlanGrade =
  (typeof SubscriptionDetailPlanGrade)[keyof typeof SubscriptionDetailPlanGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionDetailPlanGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export type SubscriptionDetailStatus =
  (typeof SubscriptionDetailStatus)[keyof typeof SubscriptionDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionDetailStatus = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  CANCELED: "CANCELED",
} as const;

export interface SubscriptionDetail {
  id?: number;
  memberId?: number;
  memberName?: string;
  planId?: number;
  planName?: string;
  planGrade?: SubscriptionDetailPlanGrade;
  planPrice?: number;
  planPeriodMonths?: number;
  billingKeyMasked?: string;
  status?: SubscriptionDetailStatus;
  cycleNo?: number;
  nextBillingAt?: string;
  startedAt?: string;
  canceledAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type PlanCreateRequestGrade =
  (typeof PlanCreateRequestGrade)[keyof typeof PlanCreateRequestGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanCreateRequestGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export interface PlanCreateRequest {
  name: string;
  grade: PlanCreateRequestGrade;
  price: number;
  periodMonths: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  pointRate: number;
  benefit?: string;
  active: string;
}

export type PlanResponseGrade =
  (typeof PlanResponseGrade)[keyof typeof PlanResponseGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanResponseGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export interface PlanResponse {
  id?: number;
  name?: string;
  grade?: PlanResponseGrade;
  price?: number;
  periodMonths?: number;
  pointRate?: number;
  benefit?: string;
  active?: string;
  activeSubscriptionCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOPlanResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PlanResponse;
}

export interface StoreDto {
  id?: number;
  regionId: number;
  /**
   * @minLength 0
   * @maxLength 120
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  address?: string;
  /**
   * @minLength 0
   * @maxLength 30
   */
  phone?: string;
  /**
   * @minimum -90
   * @maximum 90
   */
  lat: number;
  /**
   * @minimum -180
   * @maximum 180
   */
  lng: number;
  /**
   * @minLength 0
   * @maxLength 120
   */
  openHours: string;
  /**
   * @minLength 0
   * @maxLength 1
   */
  useYn?: string;
  distanceKm?: number;
  createdAt?: string;
}

export interface ResultDTOStoreDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: StoreDto;
}

export interface MemberUpdateRequest {
  name: string;
  phone?: string;
  liveYn: string;
}

export type MemberDetailUserStatus =
  (typeof MemberDetailUserStatus)[keyof typeof MemberDetailUserStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberDetailUserStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  INACTIVE: "INACTIVE",
} as const;

export type MemberDetailGrade =
  (typeof MemberDetailGrade)[keyof typeof MemberDetailGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberDetailGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export interface MemberDetail {
  id?: number;
  name?: string;
  email?: string;
  phone?: string;
  userStatus?: MemberDetailUserStatus;
  liveYn?: string;
  grade?: MemberDetailGrade;
  pointBalance?: number;
  churchId?: number;
  churchName?: string;
  regionId?: number;
  regionName?: string;
  countryId?: number;
  countryName?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOMemberDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberDetail;
}

export type InquiryDtoCategory =
  (typeof InquiryDtoCategory)[keyof typeof InquiryDtoCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryDtoCategory = {
  ACCOUNT: "ACCOUNT",
  PAYMENT: "PAYMENT",
  DELIVERY: "DELIVERY",
  CONTENT: "CONTENT",
  ETC: "ETC",
} as const;

export type InquiryDtoStatus =
  (typeof InquiryDtoStatus)[keyof typeof InquiryDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryDtoStatus = {
  OPEN: "OPEN",
  ANSWERED: "ANSWERED",
  CLOSED: "CLOSED",
} as const;

export interface InquiryDto {
  id?: number;
  memberId?: number;
  memberName?: string;
  category?: InquiryDtoCategory;
  title?: string;
  content?: string;
  status?: InquiryDtoStatus;
  answerContent?: string;
  createdAt?: string;
  answeredAt?: string;
}

export interface ResultDTOInquiryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: InquiryDto;
}

export interface InquiryAnswerRequest {
  answerContent: string;
}

export type GoodsCreateRequestStatus =
  (typeof GoodsCreateRequestStatus)[keyof typeof GoodsCreateRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsCreateRequestStatus = {
  SELLING: "SELLING",
  PAUSED: "PAUSED",
} as const;

export interface GoodsCreateRequest {
  categoryId: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  code: string;
  description?: string;
  /** @minimum 0 */
  price: number;
  /** @minimum 0 */
  listPrice?: number;
  /** @minimum 0 */
  stock?: number;
  /** @minimum 0 */
  notiQty?: number;
  soldOut?: string;
  useYn?: string;
  status?: GoodsCreateRequestStatus;
  thumbnailKey?: string;
  badges?: string[];
  options?: GoodsOptionDto[];
  images?: GoodsImageDto[];
}

export interface GoodsImageDto {
  id?: number;
  s3Key?: string;
  url?: string;
  sort?: number;
}

export interface GoodsOptionDto {
  id?: number;
  name?: string;
  optionType?: string;
  extraPrice?: number;
  stock?: number;
  useYn?: string;
  sort?: number;
}

export type GoodsDetailStatus =
  (typeof GoodsDetailStatus)[keyof typeof GoodsDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsDetailStatus = {
  SELLING: "SELLING",
  PAUSED: "PAUSED",
} as const;

export interface GoodsDetail {
  id?: number;
  categoryId?: number;
  categoryName?: string;
  name?: string;
  code?: string;
  description?: string;
  price?: number;
  listPrice?: number;
  stock?: number;
  notiQty?: number;
  soldOut?: string;
  useYn?: string;
  status?: GoodsDetailStatus;
  saleCount?: number;
  viewCount?: number;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  badges?: string;
  options?: GoodsOptionDto[];
  images?: GoodsImageDto[];
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOGoodsDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsDetail;
}

export interface GoodsBulkUpdateRequest {
  rows: Row[];
}

export interface Row {
  id: number;
  stock?: number;
  notiQty?: number;
  price?: number;
  soldOut?: string;
  useYn?: string;
  sort?: number;
}

export interface ResultDTOInteger {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: number;
}

export interface GoodsStockUpdateRequest {
  stock?: number;
  notiQty?: number;
}

export type GoodsStockDtoStatus =
  (typeof GoodsStockDtoStatus)[keyof typeof GoodsStockDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsStockDtoStatus = {
  SELLING: "SELLING",
  PAUSED: "PAUSED",
} as const;

export interface GoodsStockDto {
  id?: number;
  code?: string;
  name?: string;
  stock?: number;
  notiQty?: number;
  status?: GoodsStockDtoStatus;
  soldOut?: string;
  price?: number;
}

export interface ResultDTOGoodsStockDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsStockDto;
}

export interface GoodsReviewRatingRequest {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
}

export interface GoodsReviewDto {
  id?: number;
  goodsItemId?: number;
  memberId?: number;
  memberName?: string;
  rating?: number;
  content?: string;
  displayYn?: string;
  createdAt?: string;
}

export interface ResultDTOGoodsReviewDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsReviewDto;
}

export interface GoodsReviewDisplayRequest {
  displayYn: string;
}

export interface GoodsInquiryAnswerRequest {
  answerContent: string;
}

export type GoodsInquiryDtoAnswerStatus =
  (typeof GoodsInquiryDtoAnswerStatus)[keyof typeof GoodsInquiryDtoAnswerStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsInquiryDtoAnswerStatus = {
  WAITING: "WAITING",
  ANSWERED: "ANSWERED",
} as const;

export interface GoodsInquiryDto {
  id?: number;
  goodsItemId?: number;
  memberId?: number;
  memberName?: string;
  title?: string;
  content?: string;
  answerStatus?: GoodsInquiryDtoAnswerStatus;
  answerContent?: string;
  createdAt?: string;
  answeredAt?: string;
}

export interface ResultDTOGoodsInquiryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsInquiryDto;
}

export interface GoodsCategorySaveRequest {
  parentId?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  name: string;
  sortOrder?: number;
  /**
   * @minLength 0
   * @maxLength 1
   */
  useYn?: string;
}

export interface GoodsCategoryNodeDto {
  id?: number;
  parentId?: number;
  name?: string;
  depth?: number;
  sortOrder?: number;
  useYn?: string;
}

export interface ResultDTOGoodsCategoryNodeDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsCategoryNodeDto;
}

export type CouponDtoDiscountType =
  (typeof CouponDtoDiscountType)[keyof typeof CouponDtoDiscountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CouponDtoDiscountType = {
  AMOUNT: "AMOUNT",
  PERCENT: "PERCENT",
} as const;

export interface CouponDto {
  id?: number;
  code?: string;
  name?: string;
  discountType?: CouponDtoDiscountType;
  discountValue?: number;
  minOrderAmount?: number;
  maxDiscountAmount?: number;
  roundUnit?: number;
  startAt?: string;
  endAt?: string;
  useYn?: string;
  usageLimit?: number;
  usedCount?: number;
  createdAt?: string;
}

export interface ResultDTOCouponDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CouponDto;
}

export type ContentCreateRequestType =
  (typeof ContentCreateRequestType)[keyof typeof ContentCreateRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentCreateRequestType = {
  VIDEO: "VIDEO",
  SOUND: "SOUND",
} as const;

export type ContentCreateRequestStatus =
  (typeof ContentCreateRequestStatus)[keyof typeof ContentCreateRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentCreateRequestStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
} as const;

export interface ContentCreateRequest {
  title: string;
  description?: string;
  type: ContentCreateRequestType;
  channelId: number;
  mediaUrl?: string;
  durationSec?: number;
  thumbnailKey?: string;
  status?: ContentCreateRequestStatus;
  hashtags?: string[];
}

export type ContentDetailType =
  (typeof ContentDetailType)[keyof typeof ContentDetailType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentDetailType = {
  VIDEO: "VIDEO",
  SOUND: "SOUND",
} as const;

export type ContentDetailStatus =
  (typeof ContentDetailStatus)[keyof typeof ContentDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentDetailStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
} as const;

export interface ContentDetail {
  id?: number;
  title?: string;
  description?: string;
  type?: ContentDetailType;
  status?: ContentDetailStatus;
  channelId?: number;
  channelName?: string;
  churchName?: string;
  mediaUrl?: string;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  durationSec?: number;
  viewCount?: number;
  hashtags?: string[];
  files?: ContentFileDto[];
  createdAt?: string;
  updatedAt?: string;
}

export interface ContentFileDto {
  id?: number;
  s3Key?: string;
  url?: string;
  fileType?: string;
  sizeBytes?: number;
}

export interface ResultDTOContentDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ContentDetail;
}

export interface CommunityPostSaveRequest {
  boardId: number;
  /**
   * @minLength 0
   * @maxLength 40
   */
  category?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 2000
   */
  content?: string;
  /**
   * @minLength 0
   * @maxLength 60
   */
  writerName?: string;
  /** @pattern [YN] */
  secretYn?: string;
}

export interface CommunityPostDto {
  id?: number;
  boardId?: number;
  category?: string;
  title?: string;
  content?: string;
  writerName?: string;
  secretYn?: string;
  recommendCount?: number;
  viewCount?: number;
  createdAt?: string;
}

export interface ResultDTOCommunityPostDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CommunityPostDto;
}

export type ChurchUpsertRequestDenomination =
  (typeof ChurchUpsertRequestDenomination)[keyof typeof ChurchUpsertRequestDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChurchUpsertRequestDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export interface ChurchUpsertRequest {
  name: string;
  regionId: number;
  denomination?: ChurchUpsertRequestDenomination;
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude?: number;
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude?: number;
  address?: string;
  addressDetail?: string;
  zipcode?: string;
  phone?: string;
  pastorName?: string;
  facilities?: string;
  introduction?: string;
  homepageUrl?: string;
  thumbnailKey?: string;
  openYn?: string;
  useYn?: string;
  worshipTimes?: WorshipTimeDto[];
}

export type WorshipTimeDtoKind =
  (typeof WorshipTimeDtoKind)[keyof typeof WorshipTimeDtoKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipTimeDtoKind = {
  SUNDAY: "SUNDAY",
  DAWN: "DAWN",
  WEDNESDAY: "WEDNESDAY",
  FRIDAY: "FRIDAY",
  YOUTH: "YOUTH",
  OTHER: "OTHER",
} as const;

export interface WorshipTimeDto {
  kind?: WorshipTimeDtoKind;
  dayLabel?: string;
  startTime?: string;
  place?: string;
  target?: string;
  sort?: number;
}

export type ChurchDetailDenomination =
  (typeof ChurchDetailDenomination)[keyof typeof ChurchDetailDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChurchDetailDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export interface ChurchDetail {
  id?: number;
  name?: string;
  denomination?: ChurchDetailDenomination;
  regionId?: number;
  regionName?: string;
  address?: string;
  addressDetail?: string;
  zipcode?: string;
  phone?: string;
  pastorName?: string;
  facilities?: string;
  introduction?: string;
  homepageUrl?: string;
  latitude?: number;
  longitude?: number;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  dataSource?: string;
  openYn?: string;
  useYn?: string;
  demoData?: boolean;
  worshipTimes?: WorshipTimeDto[];
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOChurchDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChurchDetail;
}

export type CampaignDtoType =
  (typeof CampaignDtoType)[keyof typeof CampaignDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignDtoType = {
  SPECIAL_DONATION: "SPECIAL_DONATION",
  NEW_RELEASE: "NEW_RELEASE",
  EVENT: "EVENT",
  SEASONAL: "SEASONAL",
} as const;

export type CampaignDtoStatus =
  (typeof CampaignDtoStatus)[keyof typeof CampaignDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignDtoStatus = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
} as const;

export interface CampaignDto {
  id?: number;
  /**
   * @minLength 0
   * @maxLength 150
   */
  title: string;
  type: CampaignDtoType;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  bannerImageUrl?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  linkedGoodsIds?: string;
  targetAmount?: number;
  startAt: string;
  endAt: string;
  status?: CampaignDtoStatus;
  createdAt?: string;
}

export interface ResultDTOCampaignDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CampaignDto;
}

export type CampaignStatusChangeRequestStatus =
  (typeof CampaignStatusChangeRequestStatus)[keyof typeof CampaignStatusChangeRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignStatusChangeRequestStatus = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
} as const;

export interface CampaignStatusChangeRequest {
  status: CampaignStatusChangeRequestStatus;
}

export interface BoardDto {
  id?: number;
  code?: string;
  name?: string;
  readLevel?: number;
  writeLevel?: number;
  useYn?: string;
  sortOrder?: number;
  createdAt?: string;
}

export interface ResultDTOBoardDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: BoardDto;
}

export type BannerDtoPosition =
  (typeof BannerDtoPosition)[keyof typeof BannerDtoPosition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerDtoPosition = {
  MAIN_TOP: "MAIN_TOP",
  MAIN_MIDDLE: "MAIN_MIDDLE",
  MAIN_BOTTOM: "MAIN_BOTTOM",
  SIDE: "SIDE",
  POPUP: "POPUP",
} as const;

export type BannerDtoDevice =
  (typeof BannerDtoDevice)[keyof typeof BannerDtoDevice];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerDtoDevice = {
  PC: "PC",
  MOBILE: "MOBILE",
  ALL: "ALL",
} as const;

export interface BannerDto {
  id?: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  position: BannerDtoPosition;
  device: BannerDtoDevice;
  /**
   * @minLength 0
   * @maxLength 500
   */
  imageUrl: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  linkUrl?: string;
  startAt?: string;
  endAt?: string;
  sortOrder?: number;
  /**
   * @minLength 0
   * @maxLength 1
   */
  useYn?: string;
  createdAt?: string;
}

export interface ResultDTOBannerDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: BannerDto;
}

export interface BannerSortRequest {
  sortOrder?: number;
}

export type AlbumCreateRequestGenre =
  (typeof AlbumCreateRequestGenre)[keyof typeof AlbumCreateRequestGenre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumCreateRequestGenre = {
  WORSHIP: "WORSHIP",
  HYMN: "HYMN",
  GOSPEL: "GOSPEL",
  CCM: "CCM",
  CAROL: "CAROL",
  INSTRUMENTAL: "INSTRUMENTAL",
  KIDS: "KIDS",
} as const;

export type AlbumCreateRequestStatus =
  (typeof AlbumCreateRequestStatus)[keyof typeof AlbumCreateRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumCreateRequestStatus = {
  ON_SALE: "ON_SALE",
  HIDDEN: "HIDDEN",
} as const;

export interface AlbumCreateRequest {
  title: string;
  artist: string;
  label?: string;
  genre: AlbumCreateRequestGenre;
  releaseDate?: string;
  description?: string;
  coverKey?: string;
  status?: AlbumCreateRequestStatus;
  price: number;
  stock?: number;
  tracks?: TrackDto[];
}

export interface TrackDto {
  id?: number;
  trackNo?: number;
  title: string;
  durationSec?: number;
  previewUrl?: string;
  previewStartSec?: number;
  previewLengthSec?: number;
}

export type AlbumDetailGenre =
  (typeof AlbumDetailGenre)[keyof typeof AlbumDetailGenre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumDetailGenre = {
  WORSHIP: "WORSHIP",
  HYMN: "HYMN",
  GOSPEL: "GOSPEL",
  CCM: "CCM",
  CAROL: "CAROL",
  INSTRUMENTAL: "INSTRUMENTAL",
  KIDS: "KIDS",
} as const;

export type AlbumDetailStatus =
  (typeof AlbumDetailStatus)[keyof typeof AlbumDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumDetailStatus = {
  ON_SALE: "ON_SALE",
  HIDDEN: "HIDDEN",
} as const;

export type AlbumDetailSource =
  (typeof AlbumDetailSource)[keyof typeof AlbumDetailSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumDetailSource = {
  SEED: "SEED",
  EXTERNAL: "EXTERNAL",
} as const;

export interface AlbumDetail {
  id?: number;
  goodsItemId?: number;
  title?: string;
  artist?: string;
  label?: string;
  genre?: AlbumDetailGenre;
  status?: AlbumDetailStatus;
  releaseDate?: string;
  description?: string;
  coverKey?: string;
  coverUrl?: string;
  trackCount?: number;
  viewCount?: number;
  source?: AlbumDetailSource;
  price?: number;
  stock?: number;
  tracks?: TrackDto[];
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOAlbumDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: AlbumDetail;
}

export type WorshipSearchRequestStatus =
  (typeof WorshipSearchRequestStatus)[keyof typeof WorshipSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipSearchRequestStatus = {
  RECEIVED: "RECEIVED",
  CONTACTED: "CONTACTED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
} as const;

export interface WorshipSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  searchField?: string;
  keyword?: string;
  status?: WorshipSearchRequestStatus;
  churchId?: number;
  fromDate?: string;
  toDate?: string;
}

export interface ResInfinityListWorshipRegistrationListItem {
  contents?: WorshipRegistrationListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListWorshipRegistrationListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListWorshipRegistrationListItem;
}

export type WorshipRegistrationListItemStatus =
  (typeof WorshipRegistrationListItemStatus)[keyof typeof WorshipRegistrationListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationListItemStatus = {
  RECEIVED: "RECEIVED",
  CONTACTED: "CONTACTED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
} as const;

export type WorshipRegistrationListItemGender =
  (typeof WorshipRegistrationListItemGender)[keyof typeof WorshipRegistrationListItemGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationListItemGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
} as const;

export type WorshipRegistrationListItemRegisterDept =
  (typeof WorshipRegistrationListItemRegisterDept)[keyof typeof WorshipRegistrationListItemRegisterDept];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationListItemRegisterDept = {
  INFANT: "INFANT",
  CHILDREN: "CHILDREN",
  YOUTH: "YOUTH",
  YOUNG_ADULT: "YOUNG_ADULT",
  ADULT: "ADULT",
  SENIOR: "SENIOR",
} as const;

export interface WorshipRegistrationListItem {
  id?: number;
  regNo?: string;
  churchId?: number;
  churchName?: string;
  status?: WorshipRegistrationListItemStatus;
  name?: string;
  gender?: WorshipRegistrationListItemGender;
  registerDept?: WorshipRegistrationListItemRegisterDept;
  phone?: string;
  familyCount?: number;
  testMode?: string;
  createdAt?: string;
}

export type VisitSearchRequestDeviceType =
  (typeof VisitSearchRequestDeviceType)[keyof typeof VisitSearchRequestDeviceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VisitSearchRequestDeviceType = {
  PC: "PC",
  MOBILE: "MOBILE",
  TABLET: "TABLET",
} as const;

export interface VisitSearchRequest {
  fromDate?: string;
  toDate?: string;
  deviceType?: VisitSearchRequestDeviceType;
  keyword?: string;
}

export interface ResultDTOListVisitLogDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: VisitLogDto[];
}

export type VisitLogDtoDeviceType =
  (typeof VisitLogDtoDeviceType)[keyof typeof VisitLogDtoDeviceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VisitLogDtoDeviceType = {
  PC: "PC",
  MOBILE: "MOBILE",
  TABLET: "TABLET",
} as const;

export interface VisitLogDto {
  id?: number;
  visitedAt?: string;
  ipMasked?: string;
  userAgent?: string;
  browser?: string;
  os?: string;
  deviceType?: VisitLogDtoDeviceType;
  path?: string;
  memberId?: number;
}

export interface DailyCountDto {
  date?: string;
  count?: number;
}

export interface ResultDTOListDailyCountDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: DailyCountDto[];
}

export type SubscriptionSearchRequestStatus =
  (typeof SubscriptionSearchRequestStatus)[keyof typeof SubscriptionSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionSearchRequestStatus = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  CANCELED: "CANCELED",
} as const;

export interface SubscriptionSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  status?: SubscriptionSearchRequestStatus;
  planId?: number;
  churchId?: number;
}

export interface ResInfinityListSubscriptionListItem {
  contents?: SubscriptionListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListSubscriptionListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListSubscriptionListItem;
}

export type SubscriptionListItemPlanGrade =
  (typeof SubscriptionListItemPlanGrade)[keyof typeof SubscriptionListItemPlanGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionListItemPlanGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export type SubscriptionListItemStatus =
  (typeof SubscriptionListItemStatus)[keyof typeof SubscriptionListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionListItemStatus = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  CANCELED: "CANCELED",
} as const;

export interface SubscriptionListItem {
  id?: number;
  memberId?: number;
  memberName?: string;
  planId?: number;
  planName?: string;
  planGrade?: SubscriptionListItemPlanGrade;
  status?: SubscriptionListItemStatus;
  cycleNo?: number;
  billingKeyMasked?: string;
  nextBillingAt?: string;
  startedAt?: string;
}

export interface ResultDTOListStoreDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: StoreDto[];
}

export interface SmsSendRequest {
  toNumber: string;
  /**
   * @minLength 0
   * @maxLength 2000
   */
  content: string;
  memberId?: number;
}

export interface ResultDTOSmsListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: SmsListItem;
}

export type SmsListItemKind =
  (typeof SmsListItemKind)[keyof typeof SmsListItemKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmsListItemKind = {
  CUSTOM: "CUSTOM",
  ORDER_PAID: "ORDER_PAID",
  ORDER_SHIPPING: "ORDER_SHIPPING",
  DONATION_ONCE: "DONATION_ONCE",
} as const;

export type SmsListItemChannel =
  (typeof SmsListItemChannel)[keyof typeof SmsListItemChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmsListItemChannel = {
  SMS: "SMS",
  LMS: "LMS",
} as const;

export type SmsListItemStatus =
  (typeof SmsListItemStatus)[keyof typeof SmsListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmsListItemStatus = {
  QUEUED: "QUEUED",
  SENT: "SENT",
  FAILED: "FAILED",
} as const;

export interface SmsListItem {
  id?: number;
  toNumber?: string;
  content?: string;
  kind?: SmsListItemKind;
  channel?: SmsListItemChannel;
  sender?: string;
  status?: SmsListItemStatus;
  testMode?: string;
  memberId?: number;
  memberName?: string;
  refType?: string;
  refId?: string;
  sentAt?: string;
}

export type SmsSearchRequestKind =
  (typeof SmsSearchRequestKind)[keyof typeof SmsSearchRequestKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SmsSearchRequestKind = {
  CUSTOM: "CUSTOM",
  ORDER_PAID: "ORDER_PAID",
  ORDER_SHIPPING: "ORDER_SHIPPING",
  DONATION_ONCE: "DONATION_ONCE",
} as const;

export interface SmsSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  kind?: SmsSearchRequestKind;
  from?: string;
  to?: string;
}

export interface ResInfinityListSmsListItem {
  contents?: SmsListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListSmsListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListSmsListItem;
}

export interface PointLedgerSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  memberId?: number;
  churchId?: number;
}

export type PointLedgerListItemSourceType =
  (typeof PointLedgerListItemSourceType)[keyof typeof PointLedgerListItemSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PointLedgerListItemSourceType = {
  MANUAL: "MANUAL",
  EXPIRE: "EXPIRE",
  DONATION: "DONATION",
} as const;

export type PointLedgerListItemStatus =
  (typeof PointLedgerListItemStatus)[keyof typeof PointLedgerListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PointLedgerListItemStatus = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
} as const;

export interface PointLedgerListItem {
  id?: number;
  memberId?: number;
  memberName?: string;
  memberEmail?: string;
  churchId?: number;
  delta?: number;
  balanceAfter?: number;
  reason?: string;
  sourceType?: PointLedgerListItemSourceType;
  status?: PointLedgerListItemStatus;
  expireAt?: string;
  createdAt?: string;
}

export interface ResInfinityListPointLedgerListItem {
  contents?: PointLedgerListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListPointLedgerListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListPointLedgerListItem;
}

export interface PointGrantRequest {
  memberId: number;
  delta: number;
  reason: string;
  expireDays?: number;
}

export interface ResultDTOPointLedgerListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PointLedgerListItem;
}

export interface PayRequestCommand {
  orderId: number;
  provider?: string;
}

export type PaymentResultDtoStatus =
  (typeof PaymentResultDtoStatus)[keyof typeof PaymentResultDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentResultDtoStatus = {
  NONE: "NONE",
  REQUESTED: "REQUESTED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
} as const;

export interface PaymentResultDto {
  orderId?: number;
  provider?: string;
  status?: PaymentResultDtoStatus;
  txnId?: string;
  amount?: number;
  memo?: string;
  redirectUrl?: string;
  testMode?: boolean;
}

export interface ResultDTOPaymentResultDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PaymentResultDto;
}

export type PayCancelCommandToStatus =
  (typeof PayCancelCommandToStatus)[keyof typeof PayCancelCommandToStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayCancelCommandToStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface PayCancelCommand {
  orderId: number;
  toStatus?: PayCancelCommandToStatus;
  reason?: string;
}

export type PaymentSearchRequestKind =
  (typeof PaymentSearchRequestKind)[keyof typeof PaymentSearchRequestKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentSearchRequestKind = {
  PAY: "PAY",
  REFUND: "REFUND",
} as const;

export interface PaymentSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  searchField?: string;
  keyword?: string;
  kind?: PaymentSearchRequestKind;
  method?: string;
  provider?: string;
  fromDate?: string;
  toDate?: string;
}

export type PaymentListItemKind =
  (typeof PaymentListItemKind)[keyof typeof PaymentListItemKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentListItemKind = {
  PAY: "PAY",
  REFUND: "REFUND",
} as const;

export type PaymentListItemPayStatus =
  (typeof PaymentListItemPayStatus)[keyof typeof PaymentListItemPayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentListItemPayStatus = {
  NONE: "NONE",
  REQUESTED: "REQUESTED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
} as const;

export interface PaymentListItem {
  id?: number;
  orderId?: number;
  orderNo?: string;
  memberId?: number;
  memberName?: string;
  kind?: PaymentListItemKind;
  amount?: number;
  method?: string;
  provider?: string;
  txnId?: string;
  memo?: string;
  payStatus?: PaymentListItemPayStatus;
  createdAt?: string;
}

export interface ResInfinityListPaymentListItem {
  contents?: PaymentListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListPaymentListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListPaymentListItem;
}

export interface PayApproveCommand {
  orderId: number;
  txnId: string;
  cardNo?: string;
}

export type OrderSearchRequestStatus =
  (typeof OrderSearchRequestStatus)[keyof typeof OrderSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderSearchRequestStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface OrderSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  searchField?: string;
  keyword?: string;
  status?: OrderSearchRequestStatus;
  payMethod?: string;
  fromDate?: string;
  toDate?: string;
}

export type OrderListItemStatus =
  (typeof OrderListItemStatus)[keyof typeof OrderListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderListItemStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface OrderListItem {
  id?: number;
  orderNo?: string;
  memberId?: number;
  memberName?: string;
  status?: OrderListItemStatus;
  orderedName?: string;
  receiverName?: string;
  total?: number;
  payMethod?: string;
  trackingNo?: string;
  itemCount?: number;
  orderedAt?: string;
}

export interface ResInfinityListOrderListItem {
  contents?: OrderListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListOrderListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListOrderListItem;
}

export type NotificationSearchRequestChannel =
  (typeof NotificationSearchRequestChannel)[keyof typeof NotificationSearchRequestChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationSearchRequestChannel = {
  SMS: "SMS",
  PUSH: "PUSH",
  EMAIL: "EMAIL",
} as const;

export type NotificationSearchRequestStatus =
  (typeof NotificationSearchRequestStatus)[keyof typeof NotificationSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationSearchRequestStatus = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  PENDING: "PENDING",
} as const;

export interface NotificationSearchRequest {
  channel?: NotificationSearchRequestChannel;
  status?: NotificationSearchRequestStatus;
  fromDate?: string;
  toDate?: string;
  keyword?: string;
}

export type NotificationLogDtoChannel =
  (typeof NotificationLogDtoChannel)[keyof typeof NotificationLogDtoChannel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationLogDtoChannel = {
  SMS: "SMS",
  PUSH: "PUSH",
  EMAIL: "EMAIL",
} as const;

export type NotificationLogDtoStatus =
  (typeof NotificationLogDtoStatus)[keyof typeof NotificationLogDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationLogDtoStatus = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  PENDING: "PENDING",
} as const;

export interface NotificationLogDto {
  id?: number;
  channel?: NotificationLogDtoChannel;
  targetMasked?: string;
  title?: string;
  content?: string;
  status?: NotificationLogDtoStatus;
  failReason?: string;
  sentAt?: string;
  createdAt?: string;
}

export interface ResultDTOListNotificationLogDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: NotificationLogDto[];
}

export type MemberSearchRequestUserStatus =
  (typeof MemberSearchRequestUserStatus)[keyof typeof MemberSearchRequestUserStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberSearchRequestUserStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  INACTIVE: "INACTIVE",
} as const;

export interface MemberSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  userStatus?: MemberSearchRequestUserStatus;
  churchId?: number;
}

export type MemberListItemUserStatus =
  (typeof MemberListItemUserStatus)[keyof typeof MemberListItemUserStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberListItemUserStatus = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  INACTIVE: "INACTIVE",
} as const;

export type MemberListItemGrade =
  (typeof MemberListItemGrade)[keyof typeof MemberListItemGrade];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberListItemGrade = {
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  ANGEL: "ANGEL",
} as const;

export interface MemberListItem {
  id?: number;
  name?: string;
  email?: string;
  phone?: string;
  userStatus?: MemberListItemUserStatus;
  liveYn?: string;
  grade?: MemberListItemGrade;
  pointBalance?: number;
  churchId?: number;
  churchName?: string;
  regionName?: string;
  countryName?: string;
  createdAt?: string;
}

export interface ResInfinityListMemberListItem {
  contents?: MemberListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListMemberListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListMemberListItem;
}

export interface IdListRequest {
  idList: number[];
}

export type InquirySearchRequestStatus =
  (typeof InquirySearchRequestStatus)[keyof typeof InquirySearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquirySearchRequestStatus = {
  OPEN: "OPEN",
  ANSWERED: "ANSWERED",
  CLOSED: "CLOSED",
} as const;

export type InquirySearchRequestCategory =
  (typeof InquirySearchRequestCategory)[keyof typeof InquirySearchRequestCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquirySearchRequestCategory = {
  ACCOUNT: "ACCOUNT",
  PAYMENT: "PAYMENT",
  DELIVERY: "DELIVERY",
  CONTENT: "CONTENT",
  ETC: "ETC",
} as const;

export interface InquirySearchRequest {
  status?: InquirySearchRequestStatus;
  category?: InquirySearchRequestCategory;
}

export interface ResultDTOListInquiryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: InquiryDto[];
}

export interface ResultDTOUploadResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: UploadResponse;
}

export interface UploadResponse {
  key?: string;
  url?: string;
}

export type GoodsSearchRequestStatus =
  (typeof GoodsSearchRequestStatus)[keyof typeof GoodsSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsSearchRequestStatus = {
  SELLING: "SELLING",
  PAUSED: "PAUSED",
} as const;

export interface GoodsSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  categoryId?: number;
  status?: GoodsSearchRequestStatus;
  soldOut?: string;
}

export type GoodsListItemStatus =
  (typeof GoodsListItemStatus)[keyof typeof GoodsListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsListItemStatus = {
  SELLING: "SELLING",
  PAUSED: "PAUSED",
} as const;

export interface GoodsListItem {
  id?: number;
  categoryId?: number;
  categoryName?: string;
  name?: string;
  code?: string;
  price?: number;
  listPrice?: number;
  stock?: number;
  notiQty?: number;
  soldOut?: string;
  useYn?: string;
  status?: GoodsListItemStatus;
  saleCount?: number;
  viewCount?: number;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  badges?: string;
  optionCount?: number;
  createdAt?: string;
}

export interface ResInfinityListGoodsListItem {
  contents?: GoodsListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListGoodsListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListGoodsListItem;
}

export interface GoodsStockSearchRequest {
  keyword?: string;
  lowStock?: string;
  sortByStockAsc?: boolean;
}

export interface ResultDTOListGoodsStockDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsStockDto[];
}

export interface GoodsReviewSearchRequest {
  displayYn?: string;
}

export interface ResultDTOListGoodsReviewDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsReviewDto[];
}

export type GoodsInquirySearchRequestAnswerStatus =
  (typeof GoodsInquirySearchRequestAnswerStatus)[keyof typeof GoodsInquirySearchRequestAnswerStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodsInquirySearchRequestAnswerStatus = {
  WAITING: "WAITING",
  ANSWERED: "ANSWERED",
} as const;

export interface GoodsInquirySearchRequest {
  answerStatus?: GoodsInquirySearchRequestAnswerStatus;
}

export interface ResultDTOListGoodsInquiryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsInquiryDto[];
}

export interface ResultDTOListGoodsCategoryNodeDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsCategoryNodeDto[];
}

export interface OnceDonationRequest {
  memberId: number;
  amount: number;
}

export type DonationListItemType =
  (typeof DonationListItemType)[keyof typeof DonationListItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DonationListItemType = {
  ONCE: "ONCE",
  SUBSCRIPTION: "SUBSCRIPTION",
} as const;

export type DonationListItemStatus =
  (typeof DonationListItemStatus)[keyof typeof DonationListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DonationListItemStatus = {
  PAID: "PAID",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
} as const;

export interface DonationListItem {
  id?: number;
  memberId?: number;
  memberName?: string;
  subscriptionId?: number;
  planName?: string;
  type?: DonationListItemType;
  amount?: number;
  cycleNo?: number;
  status?: DonationListItemStatus;
  pointAwarded?: number;
  testMode?: string;
  paidAt?: string;
}

export interface ResultDTODonationListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: DonationListItem;
}

export type DonationSearchRequestType =
  (typeof DonationSearchRequestType)[keyof typeof DonationSearchRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DonationSearchRequestType = {
  ONCE: "ONCE",
  SUBSCRIPTION: "SUBSCRIPTION",
} as const;

export type DonationSearchRequestStatus =
  (typeof DonationSearchRequestStatus)[keyof typeof DonationSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DonationSearchRequestStatus = {
  PAID: "PAID",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
} as const;

export interface DonationSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  type?: DonationSearchRequestType;
  status?: DonationSearchRequestStatus;
  from?: string;
  to?: string;
  churchId?: number;
}

export interface ResInfinityListDonationListItem {
  contents?: DonationListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListDonationListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListDonationListItem;
}

export interface BillingCalendarRequest {
  year?: number;
  month?: number;
}

export interface BillingCalendarItem {
  date?: string;
  count?: number;
  amount?: number;
}

export interface ResultDTOListBillingCalendarItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: BillingCalendarItem[];
}

export interface CouponSearchRequest {
  useYn?: string;
  keyword?: string;
}

export interface ResultDTOListCouponDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CouponDto[];
}

export type ContentSearchRequestType =
  (typeof ContentSearchRequestType)[keyof typeof ContentSearchRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentSearchRequestType = {
  VIDEO: "VIDEO",
  SOUND: "SOUND",
} as const;

export type ContentSearchRequestStatus =
  (typeof ContentSearchRequestStatus)[keyof typeof ContentSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentSearchRequestStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
} as const;

export interface ContentSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  type?: ContentSearchRequestType;
  status?: ContentSearchRequestStatus;
  channelId?: number;
}

export type ContentListItemType =
  (typeof ContentListItemType)[keyof typeof ContentListItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentListItemType = {
  VIDEO: "VIDEO",
  SOUND: "SOUND",
} as const;

export type ContentListItemStatus =
  (typeof ContentListItemStatus)[keyof typeof ContentListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentListItemStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
} as const;

export interface ContentListItem {
  id?: number;
  title?: string;
  type?: ContentListItemType;
  status?: ContentListItemStatus;
  channelId?: number;
  channelName?: string;
  churchName?: string;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  viewCount?: number;
  durationSec?: number;
  hashtags?: string;
  createdAt?: string;
}

export interface ResInfinityListContentListItem {
  contents?: ContentListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListContentListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListContentListItem;
}

export interface CommunityPostSearchRequest {
  boardId?: number;
  category?: string;
  keyword?: string;
}

export interface ResultDTOListCommunityPostDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CommunityPostDto[];
}

export type ChurchSearchRequestDenomination =
  (typeof ChurchSearchRequestDenomination)[keyof typeof ChurchSearchRequestDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChurchSearchRequestDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export interface ChurchSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  regionId?: number;
  denomination?: ChurchSearchRequestDenomination;
  useYn?: string;
}

export type ChurchListItemDenomination =
  (typeof ChurchListItemDenomination)[keyof typeof ChurchListItemDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChurchListItemDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export interface ChurchListItem {
  id?: number;
  name?: string;
  denomination?: ChurchListItemDenomination;
  regionId?: number;
  regionName?: string;
  address?: string;
  phone?: string;
  pastorName?: string;
  latitude?: number;
  longitude?: number;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  dataSource?: string;
  openYn?: string;
  useYn?: string;
  createdAt?: string;
}

export interface ResInfinityListChurchListItem {
  contents?: ChurchListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListChurchListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListChurchListItem;
}

export interface ChatSendRequest {
  /**
   * @minLength 0
   * @maxLength 40
   */
  sessionKey: string;
  /**
   * @minLength 0
   * @maxLength 2000
   */
  message: string;
}

export type ChatReplyDtoIntent =
  (typeof ChatReplyDtoIntent)[keyof typeof ChatReplyDtoIntent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatReplyDtoIntent = {
  PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
  ORDER_LOOKUP: "ORDER_LOOKUP",
  FAQ: "FAQ",
  FALLBACK: "FALLBACK",
} as const;

export interface ChatReplyDto {
  text?: string;
  intent?: ChatReplyDtoIntent;
  quickReplies?: string[];
  testMode?: boolean;
}

export interface ResultDTOChatReplyDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChatReplyDto;
}

export type ChatSessionRowIntent =
  (typeof ChatSessionRowIntent)[keyof typeof ChatSessionRowIntent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatSessionRowIntent = {
  PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
  ORDER_LOOKUP: "ORDER_LOOKUP",
  FAQ: "FAQ",
  FALLBACK: "FALLBACK",
} as const;

export interface ChatSessionRow {
  sessionKey?: string;
  lastMessage?: string;
  lastMessageAt?: string;
  messageCount?: number;
  unanswered?: boolean;
  intent?: ChatSessionRowIntent;
}

export interface ResultDTOListChatSessionRow {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChatSessionRow[];
}

export interface ChatReplyRequest {
  /**
   * @minLength 0
   * @maxLength 2000
   */
  content: string;
}

export type ChatMessageRowRole =
  (typeof ChatMessageRowRole)[keyof typeof ChatMessageRowRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatMessageRowRole = {
  USER: "USER",
  BOT: "BOT",
} as const;

export type ChatMessageRowIntent =
  (typeof ChatMessageRowIntent)[keyof typeof ChatMessageRowIntent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatMessageRowIntent = {
  PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
  ORDER_LOOKUP: "ORDER_LOOKUP",
  FAQ: "FAQ",
  FALLBACK: "FALLBACK",
} as const;

export interface ChatMessageRow {
  id?: number;
  role?: ChatMessageRowRole;
  intent?: ChatMessageRowIntent;
  content?: string;
  createdAt?: string;
}

export interface ResultDTOChatMessageRow {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChatMessageRow;
}

export type CampaignSearchRequestType =
  (typeof CampaignSearchRequestType)[keyof typeof CampaignSearchRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignSearchRequestType = {
  SPECIAL_DONATION: "SPECIAL_DONATION",
  NEW_RELEASE: "NEW_RELEASE",
  EVENT: "EVENT",
  SEASONAL: "SEASONAL",
} as const;

export type CampaignSearchRequestStatus =
  (typeof CampaignSearchRequestStatus)[keyof typeof CampaignSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignSearchRequestStatus = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
} as const;

export interface CampaignSearchRequest {
  type?: CampaignSearchRequestType;
  status?: CampaignSearchRequestStatus;
}

export interface ResultDTOListCampaignDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CampaignDto[];
}

export interface ResultDTOListBoardDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: BoardDto[];
}

export type BannerSearchRequestPosition =
  (typeof BannerSearchRequestPosition)[keyof typeof BannerSearchRequestPosition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerSearchRequestPosition = {
  MAIN_TOP: "MAIN_TOP",
  MAIN_MIDDLE: "MAIN_MIDDLE",
  MAIN_BOTTOM: "MAIN_BOTTOM",
  SIDE: "SIDE",
  POPUP: "POPUP",
} as const;

export type BannerSearchRequestDevice =
  (typeof BannerSearchRequestDevice)[keyof typeof BannerSearchRequestDevice];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerSearchRequestDevice = {
  PC: "PC",
  MOBILE: "MOBILE",
  ALL: "ALL",
} as const;

export interface BannerSearchRequest {
  position?: BannerSearchRequestPosition;
  device?: BannerSearchRequestDevice;
  useYn?: string;
}

export interface ResultDTOListBannerDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: BannerDto[];
}

export type AlbumSearchRequestGenre =
  (typeof AlbumSearchRequestGenre)[keyof typeof AlbumSearchRequestGenre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumSearchRequestGenre = {
  WORSHIP: "WORSHIP",
  HYMN: "HYMN",
  GOSPEL: "GOSPEL",
  CCM: "CCM",
  CAROL: "CAROL",
  INSTRUMENTAL: "INSTRUMENTAL",
  KIDS: "KIDS",
} as const;

export type AlbumSearchRequestStatus =
  (typeof AlbumSearchRequestStatus)[keyof typeof AlbumSearchRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumSearchRequestStatus = {
  ON_SALE: "ON_SALE",
  HIDDEN: "HIDDEN",
} as const;

export interface AlbumSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  keyword?: string;
  genre?: AlbumSearchRequestGenre;
  status?: AlbumSearchRequestStatus;
}

export type AlbumListItemGenre =
  (typeof AlbumListItemGenre)[keyof typeof AlbumListItemGenre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumListItemGenre = {
  WORSHIP: "WORSHIP",
  HYMN: "HYMN",
  GOSPEL: "GOSPEL",
  CCM: "CCM",
  CAROL: "CAROL",
  INSTRUMENTAL: "INSTRUMENTAL",
  KIDS: "KIDS",
} as const;

export type AlbumListItemStatus =
  (typeof AlbumListItemStatus)[keyof typeof AlbumListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumListItemStatus = {
  ON_SALE: "ON_SALE",
  HIDDEN: "HIDDEN",
} as const;

export interface AlbumListItem {
  id?: number;
  title?: string;
  artist?: string;
  genre?: AlbumListItemGenre;
  status?: AlbumListItemStatus;
  coverKey?: string;
  coverUrl?: string;
  trackCount?: number;
  goodsItemId?: number;
  price?: number;
  releaseDate?: string;
  createdAt?: string;
}

export interface ResInfinityListAlbumListItem {
  contents?: AlbumListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListAlbumListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListAlbumListItem;
}

export interface ActionLogSearchRequest {
  pageNumber?: number;
  pageSize?: number;
  action?: string;
  keyword?: string;
}

export interface ActionLogItem {
  id?: number;
  adminId?: number;
  adminName?: string;
  action?: string;
  targetType?: string;
  targetId?: string;
  detail?: string;
  createdAt?: string;
}

export interface ResInfinityListActionLogItem {
  contents?: ActionLogItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListActionLogItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListActionLogItem;
}

export interface RegistrationFamilyDto {
  /**
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  relation: string;
  birthDate?: string;
}

export type WorshipRegisterRequestGender =
  (typeof WorshipRegisterRequestGender)[keyof typeof WorshipRegisterRequestGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegisterRequestGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
} as const;

export type WorshipRegisterRequestRegisterDept =
  (typeof WorshipRegisterRequestRegisterDept)[keyof typeof WorshipRegisterRequestRegisterDept];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegisterRequestRegisterDept = {
  INFANT: "INFANT",
  CHILDREN: "CHILDREN",
  YOUTH: "YOUTH",
  YOUNG_ADULT: "YOUNG_ADULT",
  ADULT: "ADULT",
  SENIOR: "SENIOR",
} as const;

export type WorshipRegisterRequestBaptismType =
  (typeof WorshipRegisterRequestBaptismType)[keyof typeof WorshipRegisterRequestBaptismType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegisterRequestBaptismType = {
  NONE: "NONE",
  BAPTISM: "BAPTISM",
  CONFIRMATION: "CONFIRMATION",
  INFANT_BAPTISM: "INFANT_BAPTISM",
} as const;

export interface WorshipRegisterRequest {
  churchId: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  gender: WorshipRegisterRequestGender;
  birthDate: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  phone: string;
  /**
   * @minLength 0
   * @maxLength 120
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 10
   */
  zipcode?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  addr1?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  addr2?: string;
  registerDept: WorshipRegisterRequestRegisterDept;
  /**
   * @minLength 0
   * @maxLength 1
   */
  churchExperience?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  prevChurch?: string;
  baptismType?: WorshipRegisterRequestBaptismType;
  /**
   * @minLength 0
   * @maxLength 50
   */
  leaderName?: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  leaderPhone?: string;
  /**
   * @minLength 0
   * @maxLength 1
   */
  privacyAgreed: string;
  families?: RegistrationFamilyDto[];
}

export interface ResultDTOWorshipRegisterResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: WorshipRegisterResponse;
}

export interface WorshipRegisterResponse {
  id?: number;
  regNo?: string;
}

export interface MemberOrderCreateRequest {
  albumId: number;
  payProvider?: string;
  couponCode?: string;
}

export type MemberOrderResultStatus =
  (typeof MemberOrderResultStatus)[keyof typeof MemberOrderResultStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberOrderResultStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface MemberOrderResult {
  orderNo?: string;
  status?: MemberOrderResultStatus;
  total?: number;
  paidAt?: string;
  testMode?: boolean;
}

export interface ResultDTOMemberOrderResult {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberOrderResult;
}

export interface MemberPaymentPrepareRequest {
  albumId: number;
  provider?: string;
  couponCode?: string;
}

export interface MemberPaymentPrepareResult {
  orderNo?: string;
  orderName?: string;
  amount?: number;
  provider?: string;
  clientKey?: string;
  customerKey?: string;
  redirectUrl?: string;
}

export interface ResultDTOMemberPaymentPrepareResult {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberPaymentPrepareResult;
}

export interface MemberPaymentConfirmRequest {
  orderNo: string;
  paymentKey: string;
  amount: number;
}

export interface EventIngestRequest {
  type?: string;
  contentType?: string;
  targetId?: number;
  title?: string;
  path?: string;
  sessionId?: string;
  memberId?: number;
  deviceType?: string;
  referrer?: string;
  dwellMs?: number;
}

export type ResultDTOVoidResultObject = { [key: string]: unknown };

export interface ResultDTOVoid {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResultDTOVoidResultObject;
}

export interface MemberLoginRequest {
  email: string;
  password: string;
}

export interface MemberAuthResponse {
  token?: string;
  expiresIn?: number;
  member?: MemberInfo;
}

export interface MemberInfo {
  id?: number;
  name?: string;
  email?: string;
  phone?: string;
  churchName?: string;
  createdAt?: string;
}

export interface ResultDTOMemberAuthResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberAuthResponse;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface ResultDTOTokenResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: TokenResponse;
}

export interface TokenResponse {
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresIn?: number;
}

export interface LoginRequest {
  loginId: string;
  password: string;
}

export type WorshipStatusChangeRequestStatus =
  (typeof WorshipStatusChangeRequestStatus)[keyof typeof WorshipStatusChangeRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipStatusChangeRequestStatus = {
  RECEIVED: "RECEIVED",
  CONTACTED: "CONTACTED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
} as const;

export interface WorshipStatusChangeRequest {
  status: WorshipStatusChangeRequestStatus;
  memo?: string;
}

export interface ResultDTOWorshipRegistrationDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: WorshipRegistrationDetail;
}

export type WorshipRegistrationDetailStatus =
  (typeof WorshipRegistrationDetailStatus)[keyof typeof WorshipRegistrationDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationDetailStatus = {
  RECEIVED: "RECEIVED",
  CONTACTED: "CONTACTED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
} as const;

export type WorshipRegistrationDetailGender =
  (typeof WorshipRegistrationDetailGender)[keyof typeof WorshipRegistrationDetailGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationDetailGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
} as const;

export type WorshipRegistrationDetailRegisterDept =
  (typeof WorshipRegistrationDetailRegisterDept)[keyof typeof WorshipRegistrationDetailRegisterDept];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationDetailRegisterDept = {
  INFANT: "INFANT",
  CHILDREN: "CHILDREN",
  YOUTH: "YOUTH",
  YOUNG_ADULT: "YOUNG_ADULT",
  ADULT: "ADULT",
  SENIOR: "SENIOR",
} as const;

export type WorshipRegistrationDetailBaptismType =
  (typeof WorshipRegistrationDetailBaptismType)[keyof typeof WorshipRegistrationDetailBaptismType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipRegistrationDetailBaptismType = {
  NONE: "NONE",
  BAPTISM: "BAPTISM",
  CONFIRMATION: "CONFIRMATION",
  INFANT_BAPTISM: "INFANT_BAPTISM",
} as const;

export interface WorshipRegistrationDetail {
  id?: number;
  regNo?: string;
  churchId?: number;
  churchName?: string;
  status?: WorshipRegistrationDetailStatus;
  name?: string;
  gender?: WorshipRegistrationDetailGender;
  birthDate?: string;
  phone?: string;
  email?: string;
  zipcode?: string;
  addr1?: string;
  addr2?: string;
  registerDept?: WorshipRegistrationDetailRegisterDept;
  churchExperience?: string;
  prevChurch?: string;
  baptismType?: WorshipRegistrationDetailBaptismType;
  leaderName?: string;
  leaderPhone?: string;
  privacyAgreed?: string;
  memo?: string;
  testMode?: string;
  families?: RegistrationFamilyDto[];
  createdAt?: string;
  updatedAt?: string;
}

export interface OrderTrackingRequest {
  trackingNo: string;
  shipCompany?: string;
}

export type OrderDetailStatus =
  (typeof OrderDetailStatus)[keyof typeof OrderDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDetailStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export type OrderDetailPayStatus =
  (typeof OrderDetailPayStatus)[keyof typeof OrderDetailPayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderDetailPayStatus = {
  NONE: "NONE",
  REQUESTED: "REQUESTED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  FAILED: "FAILED",
  CANCELED: "CANCELED",
} as const;

export interface OrderDetail {
  id?: number;
  orderNo?: string;
  memberId?: number;
  memberName?: string;
  status?: OrderDetailStatus;
  orderedName?: string;
  orderedPhone?: string;
  receiverName?: string;
  receiverPhone?: string;
  receiverAddr?: string;
  goodsTotal?: number;
  shipFee?: number;
  couponDiscount?: number;
  pointUsed?: number;
  total?: number;
  payMethod?: string;
  payProvider?: string;
  payStatus?: OrderDetailPayStatus;
  trackingNo?: string;
  shipCompany?: string;
  orderedAt?: string;
  updatedAt?: string;
  items?: OrderItemDto[];
  receipts?: OrderReceiptDto[];
}

export interface OrderItemDto {
  id?: number;
  goodsId?: number;
  optionId?: number;
  goodsName?: string;
  optionName?: string;
  unitPrice?: number;
  qty?: number;
  lineTotal?: number;
}

export type OrderReceiptDtoKind =
  (typeof OrderReceiptDtoKind)[keyof typeof OrderReceiptDtoKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderReceiptDtoKind = {
  PAY: "PAY",
  REFUND: "REFUND",
} as const;

export interface OrderReceiptDto {
  id?: number;
  kind?: OrderReceiptDtoKind;
  amount?: number;
  method?: string;
  memo?: string;
  createdAt?: string;
}

export interface ResultDTOOrderDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: OrderDetail;
}

export type OrderStatusChangeRequestStatus =
  (typeof OrderStatusChangeRequestStatus)[keyof typeof OrderStatusChangeRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatusChangeRequestStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface OrderStatusChangeRequest {
  status: OrderStatusChangeRequestStatus;
  memo?: string;
}

export interface ResultDTOTracking {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: Tracking;
}

export interface Tracking {
  carrierCode?: string;
  carrierName?: string;
  invoiceNo?: string;
  level?: number;
  completed?: boolean;
  senderName?: string;
  receiverName?: string;
  events?: TrackingEvent[];
}

export interface TrackingEvent {
  time?: string;
  location?: string;
  description?: string;
}

export interface PathCountDto {
  path?: string;
  count?: number;
}

export interface ResultDTOVisitSummaryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: VisitSummaryDto;
}

export type VisitSummaryDtoDeviceBreakdown = { [key: string]: number };

export interface VisitSummaryDto {
  totalVisits?: number;
  todayVisits?: number;
  uniqueIpApprox?: number;
  topPaths?: PathCountDto[];
  deviceBreakdown?: VisitSummaryDtoDeviceBreakdown;
}

export interface ResultDTOListPlanResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PlanResponse[];
}

export interface ChannelWatchItem {
  channelName?: string;
  totalSeconds?: number;
}

export interface ResultDTOListChannelWatchItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChannelWatchItem[];
}

export interface ResultDTOListTopContentItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: TopContentItem[];
}

export interface TopContentItem {
  id?: number;
  title?: string;
  viewCount?: number;
  channelName?: string;
}

export interface ResultDTOSummaryResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: SummaryResponse;
}

export interface SummaryResponse {
  totalMembers?: number;
  newMembers7d?: number;
  totalViews?: number;
  totalContents?: number;
}

export interface ResultDTOListTrendPoint {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: TrendPoint[];
}

export interface TrendPoint {
  date?: string;
  count?: number;
}

export type PaymentReceiptDtoKind =
  (typeof PaymentReceiptDtoKind)[keyof typeof PaymentReceiptDtoKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentReceiptDtoKind = {
  PAY: "PAY",
  REFUND: "REFUND",
} as const;

export interface PaymentReceiptDto {
  id?: number;
  orderId?: number;
  kind?: PaymentReceiptDtoKind;
  amount?: number;
  method?: string;
  memo?: string;
  provider?: string;
  txnId?: string;
  createdAt?: string;
}

export interface ResultDTOPaymentReceiptDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PaymentReceiptDto;
}

export interface Carrier {
  code?: string;
  name?: string;
  international?: boolean;
}

export interface ResultDTOListCarrier {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: Carrier[];
}

export interface ResultDTONotificationLogDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: NotificationLogDto;
}

export type NotificationSummaryDtoByChannel = { [key: string]: number };

export interface NotificationSummaryDto {
  total?: number;
  successCount?: number;
  failCount?: number;
  pendingCount?: number;
  byChannel?: NotificationSummaryDtoByChannel;
}

export interface ResultDTONotificationSummaryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: NotificationSummaryDto;
}

export interface GoodsCategoryDto {
  id?: number;
  parentId?: number;
  name?: string;
  depth?: number;
  sort?: number;
  imageKey?: string;
  imageUrl?: string;
  useYn?: string;
}

export interface ResultDTOListGoodsCategoryDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: GoodsCategoryDto[];
}

export interface ResultDTOTimeseriesResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: TimeseriesResponse;
}

export interface TimeseriesResponse {
  categories?: string[];
  goodsRevenue?: number[];
  recurringDonation?: number[];
  onceDonation?: number[];
}

export interface DashboardSummaryResponse {
  todayRevenue?: KpiDelta;
  newSubscriptions?: KpiDelta;
  openOrders?: KpiDelta;
  unansweredInquiry?: KpiDelta;
  lowStock?: KpiDelta;
  activeSubscribers?: KpiDelta;
}

export interface KpiDelta {
  current?: number;
  previous?: number;
  deltaPct?: number;
  spark?: number[];
}

export interface ResultDTODashboardSummaryResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: DashboardSummaryResponse;
}

export interface FeedItem {
  id?: string;
  kind?: string;
  message?: string;
  actorName?: string;
  occurredAt?: string;
}

export interface ResultDTOListFeedItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: FeedItem[];
}

export interface ChannelDto {
  id?: number;
  name?: string;
}

export interface ResultDTOListChannelDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChannelDto[];
}

export interface CodeLabel {
  code?: string;
  label?: string;
}

export interface ResultDTOListCodeLabel {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: CodeLabel[];
}

export type ChatHistoryItemRole =
  (typeof ChatHistoryItemRole)[keyof typeof ChatHistoryItemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatHistoryItemRole = {
  USER: "USER",
  BOT: "BOT",
} as const;

export type ChatHistoryItemIntent =
  (typeof ChatHistoryItemIntent)[keyof typeof ChatHistoryItemIntent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatHistoryItemIntent = {
  PRODUCT_INQUIRY: "PRODUCT_INQUIRY",
  ORDER_LOOKUP: "ORDER_LOOKUP",
  FAQ: "FAQ",
  FALLBACK: "FALLBACK",
} as const;

export interface ChatHistoryItem {
  role?: ChatHistoryItemRole;
  intent?: ChatHistoryItemIntent;
  content?: string;
  createdAt?: string;
}

export interface ResultDTOListChatHistoryItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChatHistoryItem[];
}

export interface ResultDTOListChatMessageRow {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChatMessageRow[];
}

export interface ResultDTOListTimeseriesPointDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: TimeseriesPointDto[];
}

export interface TimeseriesPointDto {
  date?: string;
  events?: number;
  sessions?: number;
}

export interface AnalyticsOverviewDto {
  totalEvents?: number;
  totalSessions?: number;
  uniqueVisitors?: number;
  pageViews?: number;
  contentViews?: number;
  avgDwellMs?: number;
}

export interface ResultDTOAnalyticsOverviewDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: AnalyticsOverviewDto;
}

export type ContentStatDtoContentType =
  (typeof ContentStatDtoContentType)[keyof typeof ContentStatDtoContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentStatDtoContentType = {
  VIDEO: "VIDEO",
  ALBUM: "ALBUM",
  POST: "POST",
  PAGE: "PAGE",
} as const;

export interface ContentStatDto {
  contentType?: ContentStatDtoContentType;
  targetId?: number;
  title?: string;
  views?: number;
  avgDwellMs?: number;
  lastViewedAt?: string;
}

export interface ResultDTOListContentStatDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ContentStatDto[];
}

export type AnalyticsBreakdownDtoByDevice = { [key: string]: number };

export interface AnalyticsBreakdownDto {
  byDevice?: AnalyticsBreakdownDtoByDevice;
  topReferrers?: CountItemDto[];
  topPaths?: CountItemDto[];
}

export interface CountItemDto {
  label?: string;
  count?: number;
}

export interface ResultDTOAnalyticsBreakdownDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: AnalyticsBreakdownDto;
}

export interface MeResponse {
  id?: number;
  loginId?: string;
  name?: string;
  role?: string;
  churchId?: number;
}

export interface ResultDTOMeResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MeResponse;
}

export interface ChurchOptionDto {
  id?: number;
  name?: string;
}

export interface ResultDTOListChurchOptionDto {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ChurchOptionDto[];
}

export interface PostListItem {
  id?: number;
  title?: string;
  excerpt?: string;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  createdAt?: string;
}

export interface ResInfinityListPostListItem {
  contents?: PostListItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListPostListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListPostListItem;
}

export interface PostDetail {
  id?: number;
  title?: string;
  body?: string;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ResultDTOPostDetail {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PostDetail;
}

export type MemberOrderListItemStatus =
  (typeof MemberOrderListItemStatus)[keyof typeof MemberOrderListItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberOrderListItemStatus = {
  PLACED: "PLACED",
  PAID: "PAID",
  READY: "READY",
  SHIPPING: "SHIPPING",
  DONE: "DONE",
  CANCEL: "CANCEL",
  RETURN: "RETURN",
} as const;

export interface MemberOrderListItem {
  orderNo?: string;
  productName?: string;
  total?: number;
  status?: MemberOrderListItemStatus;
  orderedAt?: string;
}

export interface ResultDTOListMemberOrderListItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberOrderListItem[];
}

export interface PublicHomeResponse {
  videos?: ContentListItem[];
  musics?: ContentListItem[];
  posts?: PostListItem[];
}

export interface ResultDTOPublicHomeResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PublicHomeResponse;
}

export type ChurchNearbyItemDenomination =
  (typeof ChurchNearbyItemDenomination)[keyof typeof ChurchNearbyItemDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChurchNearbyItemDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export interface ChurchNearbyItem {
  id?: number;
  name?: string;
  denomination?: ChurchNearbyItemDenomination;
  regionId?: number;
  regionName?: string;
  address?: string;
  phone?: string;
  pastorName?: string;
  facilities?: string;
  latitude?: number;
  longitude?: number;
  thumbnailKey?: string;
  thumbnailUrl?: string;
  dataSource?: string;
  distanceKm?: number;
}

export interface ResInfinityListChurchNearbyItem {
  contents?: ChurchNearbyItem[];
  totalCount?: number;
  totalPage?: number;
}

export interface ResultDTOResInfinityListChurchNearbyItem {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: ResInfinityListChurchNearbyItem;
}

export interface ResultDTOMemberInfo {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: MemberInfo;
}

export interface PreviewResponse {
  previewUrl?: string;
  startSec?: number;
  lengthSec?: number;
  demo?: boolean;
}

export interface ResultDTOPreviewResponse {
  resultCode?: string;
  resultMessage?: string;
  resultObject?: PreviewResponse;
}

export type GoodsUploadBody = {
  file: Blob;
};

export type ContentUploadBody = {
  file: Blob;
};

export type ChurchChurchesUploadBody = {
  file: Blob;
};

export type AlbumUploadBody = {
  file: Blob;
};

export type StatisticsTopContentsParams = {
  limit?: number;
};

export type StatisticsMemberTrendParams = {
  days?: number;
};

export type PointMemberDetailParams = {
  pageNumber?: number;
  pageSize?: number;
};

export type DashboardTimeseriesParams = {
  days?: number;
};

export type DashboardFeedParams = {
  limit?: number;
};

export type PublicStoresParams = {
  lat?: number;
  lng?: number;
  regionId?: number;
};

export type PublicPostsParams = {
  keyword?: string;
  pageNumber?: number;
  pageSize?: number;
};

export type PublicContentsParams = {
  type?: PublicContentsType;
  keyword?: string;
  pageNumber?: number;
  pageSize?: number;
};

export type PublicContentsType =
  (typeof PublicContentsType)[keyof typeof PublicContentsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicContentsType = {
  VIDEO: "VIDEO",
  SOUND: "SOUND",
} as const;

export type PublicChurchesParams = {
  lat?: number;
  lng?: number;
  radiusKm?: number;
  denomination?: PublicChurchesDenomination;
  keyword?: string;
  regionId?: number;
  pageNumber?: number;
  pageSize?: number;
};

export type PublicChurchesDenomination =
  (typeof PublicChurchesDenomination)[keyof typeof PublicChurchesDenomination];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicChurchesDenomination = {
  METHODIST: "METHODIST",
  PCK: "PCK",
  HAPDONG: "HAPDONG",
  HOLINESS: "HOLINESS",
  GOSPEL: "GOSPEL",
  BAPTIST: "BAPTIST",
  ETC: "ETC",
} as const;

export type PublicAlbumsParams = {
  genre?: PublicAlbumsGenre;
  keyword?: string;
  pageNumber?: number;
  pageSize?: number;
};

export type PublicAlbumsGenre =
  (typeof PublicAlbumsGenre)[keyof typeof PublicAlbumsGenre];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PublicAlbumsGenre = {
  WORSHIP: "WORSHIP",
  HYMN: "HYMN",
  GOSPEL: "GOSPEL",
  CCM: "CCM",
  CAROL: "CAROL",
  INSTRUMENTAL: "INSTRUMENTAL",
  KIDS: "KIDS",
} as const;
