/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (PalmPlus 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ActionLogSearchRequest,
  ResultDTOResInfinityListActionLogItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 관리자 액션 기록을 검색/페이지네이션 조회한다.
 * @summary 감사 로그 목록
 */
export const list2 = (
  actionLogSearchRequest: ActionLogSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListActionLogItem>({
    url: `/v1/action-log/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: actionLogSearchRequest,
    signal,
  });
};

export const getList2MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list2>>,
    TError,
    { data: ActionLogSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list2>>,
  TError,
  { data: ActionLogSearchRequest },
  TContext
> => {
  const mutationKey = ["list2"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list2>>,
    { data: ActionLogSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list2(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List2MutationResult = NonNullable<
  Awaited<ReturnType<typeof list2>>
>;
export type List2MutationBody = ActionLogSearchRequest;
export type List2MutationError = unknown;

/**
 * @summary 감사 로그 목록
 */
export const useList2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list2>>,
      TError,
      { data: ActionLogSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list2>>,
  TError,
  { data: ActionLogSearchRequest },
  TContext
> => {
  const mutationOptions = getList2MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
