/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  OrderSearchRequest,
  OrderStatusChangeRequest,
  OrderTrackingRequest,
  ResultDTOListCarrier,
  ResultDTOOrderDetail,
  ResultDTOResInfinityListOrderListItem,
  ResultDTOTracking,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 검색/상태/기간 필터 + 페이지네이션된 주문 목록.
 * @summary 주문 목록
 */
export const orderList = (
  orderSearchRequest: OrderSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListOrderListItem>({
    url: `/v1/order/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: orderSearchRequest,
    signal,
  });
};

export const getOrderListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderList>>,
    TError,
    { data: OrderSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof orderList>>,
  TError,
  { data: OrderSearchRequest },
  TContext
> => {
  const mutationKey = ["orderList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof orderList>>,
    { data: OrderSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return orderList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrderListMutationResult = NonNullable<
  Awaited<ReturnType<typeof orderList>>
>;
export type OrderListMutationBody = OrderSearchRequest;
export type OrderListMutationError = unknown;

/**
 * @summary 주문 목록
 */
export const useOrderList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof orderList>>,
      TError,
      { data: OrderSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof orderList>>,
  TError,
  { data: OrderSearchRequest },
  TContext
> => {
  const mutationOptions = getOrderListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 운송장 입력. READY 상태면 SHIPPING으로 자동 승격.
 * @summary 운송장 등록
 */
export const orderTracking = (
  id: number,
  orderTrackingRequest: OrderTrackingRequest
) => {
  return customInstance<ResultDTOOrderDetail>({
    url: `/v1/order/${id}/tracking`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: orderTrackingRequest,
  });
};

export const getOrderTrackingMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderTracking>>,
    TError,
    { id: number; data: OrderTrackingRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof orderTracking>>,
  TError,
  { id: number; data: OrderTrackingRequest },
  TContext
> => {
  const mutationKey = ["orderTracking"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof orderTracking>>,
    { id: number; data: OrderTrackingRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return orderTracking(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrderTrackingMutationResult = NonNullable<
  Awaited<ReturnType<typeof orderTracking>>
>;
export type OrderTrackingMutationBody = OrderTrackingRequest;
export type OrderTrackingMutationError = unknown;

/**
 * @summary 운송장 등록
 */
export const useOrderTracking = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof orderTracking>>,
      TError,
      { id: number; data: OrderTrackingRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof orderTracking>>,
  TError,
  { id: number; data: OrderTrackingRequest },
  TContext
> => {
  const mutationOptions = getOrderTrackingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 상태머신 전이 + 재고 차감/복원 + 입금/환불 영수증을 한 트랜잭션으로 처리.
 * @summary 주문 상태 변경
 */
export const orderStatus = (
  id: number,
  orderStatusChangeRequest: OrderStatusChangeRequest
) => {
  return customInstance<ResultDTOOrderDetail>({
    url: `/v1/order/${id}/status`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: orderStatusChangeRequest,
  });
};

export const getOrderStatusMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderStatus>>,
    TError,
    { id: number; data: OrderStatusChangeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof orderStatus>>,
  TError,
  { id: number; data: OrderStatusChangeRequest },
  TContext
> => {
  const mutationKey = ["orderStatus"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof orderStatus>>,
    { id: number; data: OrderStatusChangeRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return orderStatus(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrderStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof orderStatus>>
>;
export type OrderStatusMutationBody = OrderStatusChangeRequest;
export type OrderStatusMutationError = unknown;

/**
 * @summary 주문 상태 변경
 */
export const useOrderStatus = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof orderStatus>>,
      TError,
      { id: number; data: OrderStatusChangeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof orderStatus>>,
  TError,
  { id: number; data: OrderStatusChangeRequest },
  TContext
> => {
  const mutationOptions = getOrderStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 택배사 배송상태를 조회하고, 배달완료면 주문을 DONE으로(이동중이면 SHIPPING으로) 자동 전이한다.
 * @summary 배송 조회·상태 동기화
 */
export const orderDeliverySyncUpdate = (id: number) => {
  return customInstance<ResultDTOTracking>({
    url: `/v1/order/${id}/delivery-sync`,
    method: "PATCH",
  });
};

export const getOrderDeliverySyncUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof orderDeliverySyncUpdate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof orderDeliverySyncUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["orderDeliverySyncUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof orderDeliverySyncUpdate>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return orderDeliverySyncUpdate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type OrderDeliverySyncUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof orderDeliverySyncUpdate>>
>;

export type OrderDeliverySyncUpdateMutationError = unknown;

/**
 * @summary 배송 조회·상태 동기화
 */
export const useOrderDeliverySyncUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof orderDeliverySyncUpdate>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof orderDeliverySyncUpdate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getOrderDeliverySyncUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 주문 + 주문상품 + 입금/환불 영수증.
 * @summary 주문 상세
 */
export const orderDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOOrderDetail>({
    url: `/v1/order/${id}`,
    method: "GET",
    signal,
  });
};

export const getOrderDetailQueryKey = (id?: number) => {
  return [`/v1/order/${id}`] as const;
};

export const getOrderDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof orderDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrderDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof orderDetail>>> = ({
    signal,
  }) => orderDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof orderDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrderDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof orderDetail>>
>;
export type OrderDetailQueryError = unknown;

export function useOrderDetail<
  TData = Awaited<ReturnType<typeof orderDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderDetail>>,
          TError,
          Awaited<ReturnType<typeof orderDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderDetail<
  TData = Awaited<ReturnType<typeof orderDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderDetail>>,
          TError,
          Awaited<ReturnType<typeof orderDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderDetail<
  TData = Awaited<ReturnType<typeof orderDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 주문 상세
 */

export function useOrderDetail<
  TData = Awaited<ReturnType<typeof orderDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getOrderDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 주문의 택배사+운송장번호로 택배사 API를 호출해 실시간 배송 진행상황을 반환한다(상태 변경 없음).
 * @summary 배송 조회
 */
export const orderTrackingInfo = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOTracking>({
    url: `/v1/order/${id}/tracking-info`,
    method: "GET",
    signal,
  });
};

export const getOrderTrackingInfoQueryKey = (id?: number) => {
  return [`/v1/order/${id}/tracking-info`] as const;
};

export const getOrderTrackingInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof orderTrackingInfo>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof orderTrackingInfo>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrderTrackingInfoQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof orderTrackingInfo>>
  > = ({ signal }) => orderTrackingInfo(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof orderTrackingInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrderTrackingInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof orderTrackingInfo>>
>;
export type OrderTrackingInfoQueryError = unknown;

export function useOrderTrackingInfo<
  TData = Awaited<ReturnType<typeof orderTrackingInfo>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof orderTrackingInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderTrackingInfo>>,
          TError,
          Awaited<ReturnType<typeof orderTrackingInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderTrackingInfo<
  TData = Awaited<ReturnType<typeof orderTrackingInfo>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof orderTrackingInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderTrackingInfo>>,
          TError,
          Awaited<ReturnType<typeof orderTrackingInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderTrackingInfo<
  TData = Awaited<ReturnType<typeof orderTrackingInfo>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof orderTrackingInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 배송 조회
 */

export function useOrderTrackingInfo<
  TData = Awaited<ReturnType<typeof orderTrackingInfo>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof orderTrackingInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getOrderTrackingInfoQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 운송장 등록 드롭다운용 택배사 목록(스마트택배 연동).
 * @summary 택배사 목록
 */
export const orderCarriers = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListCarrier>({
    url: `/v1/order/carriers`,
    method: "GET",
    signal,
  });
};

export const getOrderCarriersQueryKey = () => {
  return [`/v1/order/carriers`] as const;
};

export const getOrderCarriersQueryOptions = <
  TData = Awaited<ReturnType<typeof orderCarriers>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof orderCarriers>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOrderCarriersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof orderCarriers>>> = ({
    signal,
  }) => orderCarriers(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof orderCarriers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OrderCarriersQueryResult = NonNullable<
  Awaited<ReturnType<typeof orderCarriers>>
>;
export type OrderCarriersQueryError = unknown;

export function useOrderCarriers<
  TData = Awaited<ReturnType<typeof orderCarriers>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderCarriers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderCarriers>>,
          TError,
          Awaited<ReturnType<typeof orderCarriers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderCarriers<
  TData = Awaited<ReturnType<typeof orderCarriers>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderCarriers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof orderCarriers>>,
          TError,
          Awaited<ReturnType<typeof orderCarriers>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useOrderCarriers<
  TData = Awaited<ReturnType<typeof orderCarriers>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderCarriers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 택배사 목록
 */

export function useOrderCarriers<
  TData = Awaited<ReturnType<typeof orderCarriers>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof orderCarriers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getOrderCarriersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
