/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BillingCalendarRequest,
  DonationSearchRequest,
  OnceDonationRequest,
  ResultDTODonationListItem,
  ResultDTOInteger,
  ResultDTOListBillingCalendarItem,
  ResultDTOResInfinityListDonationListItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 데모용 — 도래한 구독을 즉시 청구하고 처리 건수를 반환한다(SYSTEM 전용).
 * @summary 정기청구 수동 실행
 */
export const runBilling = (signal?: AbortSignal) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/donation/run-billing`,
    method: "POST",
    signal,
  });
};

export const getRunBillingMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runBilling>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runBilling>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["runBilling"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runBilling>>,
    void
  > = () => {
    return runBilling();
  };

  return { mutationFn, ...mutationOptions };
};

export type RunBillingMutationResult = NonNullable<
  Awaited<ReturnType<typeof runBilling>>
>;

export type RunBillingMutationError = unknown;

/**
 * @summary 정기청구 수동 실행
 */
export const useRunBilling = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof runBilling>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof runBilling>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getRunBillingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 수기 단건 후원 등록(테스트 모드).
 * @summary 단건 후원 등록
 */
export const createOnce = (
  onceDonationRequest: OnceDonationRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTODonationListItem>({
    url: `/v1/donation/once`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: onceDonationRequest,
    signal,
  });
};

export const getCreateOnceMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOnce>>,
    TError,
    { data: OnceDonationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOnce>>,
  TError,
  { data: OnceDonationRequest },
  TContext
> => {
  const mutationKey = ["createOnce"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOnce>>,
    { data: OnceDonationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createOnce(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOnceMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOnce>>
>;
export type CreateOnceMutationBody = OnceDonationRequest;
export type CreateOnceMutationError = unknown;

/**
 * @summary 단건 후원 등록
 */
export const useCreateOnce = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOnce>>,
      TError,
      { data: OnceDonationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createOnce>>,
  TError,
  { data: OnceDonationRequest },
  TContext
> => {
  const mutationOptions = getCreateOnceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 유형/상태/기간 필터 + 페이지네이션.
 * @summary 후원 내역 목록
 */
export const list5 = (
  donationSearchRequest: DonationSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListDonationListItem>({
    url: `/v1/donation/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: donationSearchRequest,
    signal,
  });
};

export const getList5MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list5>>,
    TError,
    { data: DonationSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list5>>,
  TError,
  { data: DonationSearchRequest },
  TContext
> => {
  const mutationKey = ["list5"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list5>>,
    { data: DonationSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list5(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List5MutationResult = NonNullable<
  Awaited<ReturnType<typeof list5>>
>;
export type List5MutationBody = DonationSearchRequest;
export type List5MutationError = unknown;

/**
 * @summary 후원 내역 목록
 */
export const useList5 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list5>>,
      TError,
      { data: DonationSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list5>>,
  TError,
  { data: DonationSearchRequest },
  TContext
> => {
  const mutationOptions = getList5MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 활성 구독의 월별 청구 예정 집계(날짜별 건수·금액).
 * @summary 결제일정 캘린더
 */
export const calendar = (
  billingCalendarRequest: BillingCalendarRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListBillingCalendarItem>({
    url: `/v1/donation/calendar`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: billingCalendarRequest,
    signal,
  });
};

export const getCalendarMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof calendar>>,
    TError,
    { data: BillingCalendarRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof calendar>>,
  TError,
  { data: BillingCalendarRequest },
  TContext
> => {
  const mutationKey = ["calendar"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof calendar>>,
    { data: BillingCalendarRequest }
  > = (props) => {
    const { data } = props ?? {};

    return calendar(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CalendarMutationResult = NonNullable<
  Awaited<ReturnType<typeof calendar>>
>;
export type CalendarMutationBody = BillingCalendarRequest;
export type CalendarMutationError = unknown;

/**
 * @summary 결제일정 캘린더
 */
export const useCalendar = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof calendar>>,
      TError,
      { data: BillingCalendarRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof calendar>>,
  TError,
  { data: BillingCalendarRequest },
  TContext
> => {
  const mutationOptions = getCalendarMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
