/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResultDTOListChurchOptionDto,
  ResultDTOWorshipRegisterResponse,
  WorshipRegisterRequest,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 비회원 다단계 폼 제출 → 신청 1건 + 가족 N건(최대 5) 생성. 실제 알림 미발송. 과도한 요청은 429.
 * @summary 공개 신청 생성
 */
export const worshipPublicWorshipCreate = (
  worshipRegisterRequest: WorshipRegisterRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOWorshipRegisterResponse>({
    url: `/pub/v1/worship`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: worshipRegisterRequest,
    signal,
  });
};

export const getWorshipPublicWorshipCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof worshipPublicWorshipCreate>>,
    TError,
    { data: WorshipRegisterRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof worshipPublicWorshipCreate>>,
  TError,
  { data: WorshipRegisterRequest },
  TContext
> => {
  const mutationKey = ["worshipPublicWorshipCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof worshipPublicWorshipCreate>>,
    { data: WorshipRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return worshipPublicWorshipCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type WorshipPublicWorshipCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof worshipPublicWorshipCreate>>
>;
export type WorshipPublicWorshipCreateMutationBody = WorshipRegisterRequest;
export type WorshipPublicWorshipCreateMutationError = unknown;

/**
 * @summary 공개 신청 생성
 */
export const useWorshipPublicWorshipCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof worshipPublicWorshipCreate>>,
      TError,
      { data: WorshipRegisterRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof worshipPublicWorshipCreate>>,
  TError,
  { data: WorshipRegisterRequest },
  TContext
> => {
  const mutationOptions = getWorshipPublicWorshipCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 신청 폼의 교회 선택용 (openYn='Y'만).
 * @summary 공개 교회 목록
 */
export const worshipPublicWorshipChurches = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListChurchOptionDto>({
    url: `/pub/v1/worship/churches`,
    method: "GET",
    signal,
  });
};

export const getWorshipPublicWorshipChurchesQueryKey = () => {
  return [`/pub/v1/worship/churches`] as const;
};

export const getWorshipPublicWorshipChurchesQueryOptions = <
  TData = Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWorshipPublicWorshipChurchesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof worshipPublicWorshipChurches>>
  > = ({ signal }) => worshipPublicWorshipChurches(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WorshipPublicWorshipChurchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof worshipPublicWorshipChurches>>
>;
export type WorshipPublicWorshipChurchesQueryError = unknown;

export function useWorshipPublicWorshipChurches<
  TData = Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
          TError,
          Awaited<ReturnType<typeof worshipPublicWorshipChurches>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorshipPublicWorshipChurches<
  TData = Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
          TError,
          Awaited<ReturnType<typeof worshipPublicWorshipChurches>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWorshipPublicWorshipChurches<
  TData = Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 교회 목록
 */

export function useWorshipPublicWorshipChurches<
  TData = Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof worshipPublicWorshipChurches>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getWorshipPublicWorshipChurchesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
