/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  LoginRequest,
  RefreshRequest,
  ResultDTOTokenResponse,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * refresh 토큰으로 새 토큰 쌍을 발급한다.
 * @summary 토큰 갱신
 */
export const refresh = (
  refreshRequest: RefreshRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOTokenResponse>({
    url: `/auth/refresh`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: refreshRequest,
    signal,
  });
};

export const getRefreshMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refresh>>,
    TError,
    { data: RefreshRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refresh>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationKey = ["refresh"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refresh>>,
    { data: RefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return refresh(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof refresh>>
>;
export type RefreshMutationBody = RefreshRequest;
export type RefreshMutationError = unknown;

/**
 * @summary 토큰 갱신
 */
export const useRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refresh>>,
      TError,
      { data: RefreshRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof refresh>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationOptions = getRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * refresh 토큰을 무효화한다.
 * @summary 로그아웃
 */
export const logout = (
  refreshRequest: RefreshRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/auth/logout`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: refreshRequest,
    signal,
  });
};

export const getLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    { data: RefreshRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    { data: RefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return logout(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;
export type LogoutMutationBody = RefreshRequest;
export type LogoutMutationError = unknown;

/**
 * @summary 로그아웃
 */
export const useLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logout>>,
      TError,
      { data: RefreshRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  { data: RefreshRequest },
  TContext
> => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 아이디/비밀번호로 access/refresh 토큰을 발급한다.
 * @summary 로그인
 */
export const login1 = (loginRequest: LoginRequest, signal?: AbortSignal) => {
  return customInstance<ResultDTOTokenResponse>({
    url: `/auth/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: loginRequest,
    signal,
  });
};

export const getLogin1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login1>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login1>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationKey = ["login1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login1>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return login1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Login1MutationResult = NonNullable<
  Awaited<ReturnType<typeof login1>>
>;
export type Login1MutationBody = LoginRequest;
export type Login1MutationError = unknown;

/**
 * @summary 로그인
 */
export const useLogin1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login1>>,
      TError,
      { data: LoginRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof login1>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationOptions = getLogin1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
