/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../custom-instance";

/**
 * 음원 콘텐츠의 플레이리스트. 비암호·무인증(PUBLISHED만).
 * @summary 음원 콘텐츠 스트림(공개 HLS)
 */
export const publicHLSContentsHlsIndexM3u8 = (
  contentId: number,
  signal?: AbortSignal
) => {
  return customInstance<string>({
    url: `/pub/v1/contents/${contentId}/hls/index.m3u8`,
    method: "GET",
    signal,
  });
};

export const getPublicHLSContentsHlsIndexM3u8QueryKey = (
  contentId?: number
) => {
  return [`/pub/v1/contents/${contentId}/hls/index.m3u8`] as const;
};

export const getPublicHLSContentsHlsIndexM3u8QueryOptions = <
  TData = Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
  TError = unknown
>(
  contentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPublicHLSContentsHlsIndexM3u8QueryKey(contentId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>
  > = ({ signal }) => publicHLSContentsHlsIndexM3u8(contentId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!contentId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicHLSContentsHlsIndexM3u8QueryResult = NonNullable<
  Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>
>;
export type PublicHLSContentsHlsIndexM3u8QueryError = unknown;

export function usePublicHLSContentsHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
  TError = unknown
>(
  contentId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHLSContentsHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
  TError = unknown
>(
  contentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHLSContentsHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
  TError = unknown
>(
  contentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 음원 콘텐츠 스트림(공개 HLS)
 */

export function usePublicHLSContentsHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
  TError = unknown
>(
  contentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSContentsHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicHLSContentsHlsIndexM3u8QueryOptions(
    contentId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 트랙의 30초 미리듣기 플레이리스트. 비암호·무인증.
 * @summary 프리뷰 스트림(공개 HLS)
 */
export const publicHLSAlbumsTracksPreviewIndexM3u8 = (
  albumId: number,
  trackId: number,
  signal?: AbortSignal
) => {
  return customInstance<string>({
    url: `/pub/v1/albums/${albumId}/tracks/${trackId}/preview/index.m3u8`,
    method: "GET",
    signal,
  });
};

export const getPublicHLSAlbumsTracksPreviewIndexM3u8QueryKey = (
  albumId?: number,
  trackId?: number
) => {
  return [
    `/pub/v1/albums/${albumId}/tracks/${trackId}/preview/index.m3u8`,
  ] as const;
};

export const getPublicHLSAlbumsTracksPreviewIndexM3u8QueryOptions = <
  TData = Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPublicHLSAlbumsTracksPreviewIndexM3u8QueryKey(albumId, trackId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>
  > = ({ signal }) =>
    publicHLSAlbumsTracksPreviewIndexM3u8(albumId, trackId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(albumId && trackId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicHLSAlbumsTracksPreviewIndexM3u8QueryResult = NonNullable<
  Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>
>;
export type PublicHLSAlbumsTracksPreviewIndexM3u8QueryError = unknown;

export function usePublicHLSAlbumsTracksPreviewIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHLSAlbumsTracksPreviewIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicHLSAlbumsTracksPreviewIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 프리뷰 스트림(공개 HLS)
 */

export function usePublicHLSAlbumsTracksPreviewIndexM3u8<
  TData = Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicHLSAlbumsTracksPreviewIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPublicHLSAlbumsTracksPreviewIndexM3u8QueryOptions(
    albumId,
    trackId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
