/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PlanCreateRequest,
  ResultDTOListPlanResponse,
  ResultDTOPlanResponse,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 멤버십 플랜 상세
 */
export const detail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPlanResponse>({
    url: `/v1/subscription-plan/${id}`,
    method: "GET",
    signal,
  });
};

export const getDetailQueryKey = (id?: number) => {
  return [`/v1/subscription-plan/${id}`] as const;
};

export const getDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail>>> = ({
    signal,
  }) => detail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DetailQueryResult = NonNullable<Awaited<ReturnType<typeof detail>>>;
export type DetailQueryError = unknown;

export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 멤버십 플랜 상세
 */

export function useDetail<
  TData = Awaited<ReturnType<typeof detail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 멤버십 플랜 수정
 */
export const update = (id: number, planCreateRequest: PlanCreateRequest) => {
  return customInstance<ResultDTOPlanResponse>({
    url: `/v1/subscription-plan/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: planCreateRequest,
  });
};

export const getUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { id: number; data: PlanCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { id: number; data: PlanCreateRequest },
  TContext
> => {
  const mutationKey = ["update"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { id: number; data: PlanCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof update>>
>;
export type UpdateMutationBody = PlanCreateRequest;
export type UpdateMutationError = unknown;

/**
 * @summary 멤버십 플랜 수정
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { id: number; data: PlanCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { id: number; data: PlanCreateRequest },
  TContext
> => {
  const mutationOptions = getUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 파괴적 액션 — SYSTEM 전용.
 * @summary 멤버십 플랜 삭제
 */
export const _delete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/subscription-plan/${id}`,
    method: "DELETE",
  });
};

export const getDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["_delete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return _delete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof _delete>>
>;

export type _DeleteMutationError = unknown;

/**
 * @summary 멤버십 플랜 삭제
 */
export const useDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 멤버십 플랜 등록
 */
export const create = (
  planCreateRequest: PlanCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOPlanResponse>({
    url: `/v1/subscription-plan`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: planCreateRequest,
    signal,
  });
};

export const getCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: PlanCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: PlanCreateRequest },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: PlanCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof create>>
>;
export type CreateMutationBody = PlanCreateRequest;
export type CreateMutationError = unknown;

/**
 * @summary 멤버십 플랜 등록
 */
export const useCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { data: PlanCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: PlanCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 가격 오름차순 전체 플랜 목록.
 * @summary 멤버십 플랜 목록
 */
export const list8 = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListPlanResponse>({
    url: `/v1/subscription-plan/list`,
    method: "GET",
    signal,
  });
};

export const getList8QueryKey = () => {
  return [`/v1/subscription-plan/list`] as const;
};

export const getList8QueryOptions = <
  TData = Awaited<ReturnType<typeof list8>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof list8>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getList8QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list8>>> = ({
    signal,
  }) => list8(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof list8>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type List8QueryResult = NonNullable<Awaited<ReturnType<typeof list8>>>;
export type List8QueryError = unknown;

export function useList8<
  TData = Awaited<ReturnType<typeof list8>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list8>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list8>>,
          TError,
          Awaited<ReturnType<typeof list8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList8<
  TData = Awaited<ReturnType<typeof list8>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list8>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list8>>,
          TError,
          Awaited<ReturnType<typeof list8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useList8<
  TData = Awaited<ReturnType<typeof list8>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list8>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 멤버십 플랜 목록
 */

export function useList8<
  TData = Awaited<ReturnType<typeof list8>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof list8>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getList8QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
