/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { ResultDTOArchiveResult } from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 보관 기간이 지난 감사/보안 로그를 S3에 아카이브 후 삭제하고 처리 건수를 반환한다.
 * @summary 로그 아카이브 수동 실행
 */
export const logArchiveAdminLogArchiveRunCreate = (signal?: AbortSignal) => {
  return customInstance<ResultDTOArchiveResult>({
    url: `/v1/admin/log-archive/run`,
    method: "POST",
    signal,
  });
};

export const getLogArchiveAdminLogArchiveRunCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logArchiveAdminLogArchiveRunCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>,
    void
  > = () => {
    return logArchiveAdminLogArchiveRunCreate();
  };

  return { mutationFn, ...mutationOptions };
};

export type LogArchiveAdminLogArchiveRunCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>
>;

export type LogArchiveAdminLogArchiveRunCreateMutationError = unknown;

/**
 * @summary 로그 아카이브 수동 실행
 */
export const useLogArchiveAdminLogArchiveRunCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof logArchiveAdminLogArchiveRunCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getLogArchiveAdminLogArchiveRunCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
