/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GoodsBulkUpdateRequest,
  GoodsCreateRequest,
  GoodsSearchRequest,
  ResultDTOGoodsDetail,
  ResultDTOInteger,
  ResultDTOListGoodsCategoryDto,
  ResultDTOResInfinityListGoodsListItem,
  ResultDTOUploadResponse,
  ResultDTOVoid,
  UploadBody,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 굿즈 상세
 */
export const detail2 = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods/${id}`,
    method: "GET",
    signal,
  });
};

export const getDetail2QueryKey = (id?: number) => {
  return [`/v1/goods/${id}`] as const;
};

export const getDetail2QueryOptions = <
  TData = Awaited<ReturnType<typeof detail2>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetail2QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail2>>> = ({
    signal,
  }) => detail2(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Detail2QueryResult = NonNullable<
  Awaited<ReturnType<typeof detail2>>
>;
export type Detail2QueryError = unknown;

export function useDetail2<
  TData = Awaited<ReturnType<typeof detail2>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail2>>,
          TError,
          Awaited<ReturnType<typeof detail2>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail2<
  TData = Awaited<ReturnType<typeof detail2>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail2>>,
          TError,
          Awaited<ReturnType<typeof detail2>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail2<
  TData = Awaited<ReturnType<typeof detail2>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 굿즈 상세
 */

export function useDetail2<
  TData = Awaited<ReturnType<typeof detail2>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail2>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetail2QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 굿즈 수정
 */
export const update2 = (id: number, goodsCreateRequest: GoodsCreateRequest) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsCreateRequest,
  });
};

export const getUpdate2MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update2>>,
    TError,
    { id: number; data: GoodsCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update2>>,
  TError,
  { id: number; data: GoodsCreateRequest },
  TContext
> => {
  const mutationKey = ["update2"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update2>>,
    { id: number; data: GoodsCreateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update2(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update2MutationResult = NonNullable<
  Awaited<ReturnType<typeof update2>>
>;
export type Update2MutationBody = GoodsCreateRequest;
export type Update2MutationError = unknown;

/**
 * @summary 굿즈 수정
 */
export const useUpdate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update2>>,
      TError,
      { id: number; data: GoodsCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof update2>>,
  TError,
  { id: number; data: GoodsCreateRequest },
  TContext
> => {
  const mutationOptions = getUpdate2MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 굿즈 삭제
 */
export const delete1 = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/goods/${id}`,
    method: "DELETE",
  });
};

export const getDelete1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete1>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["delete1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete1>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return delete1(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete1MutationResult = NonNullable<
  Awaited<ReturnType<typeof delete1>>
>;

export type Delete1MutationError = unknown;

/**
 * @summary 굿즈 삭제
 */
export const useDelete1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete1>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDelete1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * AG Grid에서 변경된 행만 반영. 반영 행수를 반환.
 * @summary 굿즈 인라인 일괄수정
 */
export const bulkUpdate = (goodsBulkUpdateRequest: GoodsBulkUpdateRequest) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/goods/bulk`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: goodsBulkUpdateRequest,
  });
};

export const getBulkUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkUpdate>>,
    TError,
    { data: GoodsBulkUpdateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkUpdate>>,
  TError,
  { data: GoodsBulkUpdateRequest },
  TContext
> => {
  const mutationKey = ["bulkUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkUpdate>>,
    { data: GoodsBulkUpdateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return bulkUpdate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BulkUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkUpdate>>
>;
export type BulkUpdateMutationBody = GoodsBulkUpdateRequest;
export type BulkUpdateMutationError = unknown;

/**
 * @summary 굿즈 인라인 일괄수정
 */
export const useBulkUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bulkUpdate>>,
      TError,
      { data: GoodsBulkUpdateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof bulkUpdate>>,
  TError,
  { data: GoodsBulkUpdateRequest },
  TContext
> => {
  const mutationOptions = getBulkUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 굿즈 등록
 */
export const create1 = (
  goodsCreateRequest: GoodsCreateRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOGoodsDetail>({
    url: `/v1/goods`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsCreateRequest,
    signal,
  });
};

export const getCreate1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { data: GoodsCreateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: GoodsCreateRequest },
  TContext
> => {
  const mutationKey = ["create1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { data: GoodsCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<
  Awaited<ReturnType<typeof create1>>
>;
export type Create1MutationBody = GoodsCreateRequest;
export type Create1MutationError = unknown;

/**
 * @summary 굿즈 등록
 */
export const useCreate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { data: GoodsCreateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: GoodsCreateRequest },
  TContext
> => {
  const mutationOptions = getCreate1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 썸네일/추가 이미지를 스토리지에 업로드하고 key/url을 반환한다.
 * @summary 굿즈 이미지 업로드
 */
export const upload = (uploadBody: UploadBody, signal?: AbortSignal) => {
  return customInstance<ResultDTOUploadResponse>({
    url: `/v1/goods/upload`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: uploadBody,
    signal,
  });
};

export const getUploadMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof upload>>,
    TError,
    { data: UploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  const mutationKey = ["upload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof upload>>,
    { data: UploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return upload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof upload>>
>;
export type UploadMutationBody = UploadBody;
export type UploadMutationError = unknown;

/**
 * @summary 굿즈 이미지 업로드
 */
export const useUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof upload>>,
      TError,
      { data: UploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof upload>>,
  TError,
  { data: UploadBody },
  TContext
> => {
  const mutationOptions = getUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 굿즈 상품 목록.
 * @summary 굿즈 목록
 */
export const list4 = (
  goodsSearchRequest: GoodsSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListGoodsListItem>({
    url: `/v1/goods/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: goodsSearchRequest,
    signal,
  });
};

export const getList4MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list4>>,
    TError,
    { data: GoodsSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list4>>,
  TError,
  { data: GoodsSearchRequest },
  TContext
> => {
  const mutationKey = ["list4"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list4>>,
    { data: GoodsSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list4(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List4MutationResult = NonNullable<
  Awaited<ReturnType<typeof list4>>
>;
export type List4MutationBody = GoodsSearchRequest;
export type List4MutationError = unknown;

/**
 * @summary 굿즈 목록
 */
export const useList4 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list4>>,
      TError,
      { data: GoodsSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list4>>,
  TError,
  { data: GoodsSearchRequest },
  TContext
> => {
  const mutationOptions = getList4MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 굿즈 등록 폼의 분류 선택용 트리.
 * @summary 굿즈 카테고리 트리
 */
export const categories = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListGoodsCategoryDto>({
    url: `/v1/goods/categories`,
    method: "GET",
    signal,
  });
};

export const getCategoriesQueryKey = () => {
  return [`/v1/goods/categories`] as const;
};

export const getCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof categories>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof categories>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof categories>>> = ({
    signal,
  }) => categories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof categories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof categories>>
>;
export type CategoriesQueryError = unknown;

export function useCategories<
  TData = Awaited<ReturnType<typeof categories>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categories>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof categories>>,
          TError,
          Awaited<ReturnType<typeof categories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategories<
  TData = Awaited<ReturnType<typeof categories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categories>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof categories>>,
          TError,
          Awaited<ReturnType<typeof categories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCategories<
  TData = Awaited<ReturnType<typeof categories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 굿즈 카테고리 트리
 */

export function useCategories<
  TData = Awaited<ReturnType<typeof categories>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof categories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
