/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../custom-instance";

/**
 * 해당 앨범을 구매한 회원에게만 16바이트 키를 반환. 캐시 금지.
 * @summary AES-128 키
 */
export const albumHLSAlbumsTracksHlsKey = (
  albumId: number,
  trackId: number,
  signal?: AbortSignal
) => {
  return customInstance<string>({
    url: `/pub/v1/albums/${albumId}/tracks/${trackId}/hls/key`,
    method: "GET",
    signal,
  });
};

export const getAlbumHLSAlbumsTracksHlsKeyQueryKey = (
  albumId?: number,
  trackId?: number
) => {
  return [`/pub/v1/albums/${albumId}/tracks/${trackId}/hls/key`] as const;
};

export const getAlbumHLSAlbumsTracksHlsKeyQueryOptions = <
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAlbumHLSAlbumsTracksHlsKeyQueryKey(albumId, trackId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>
  > = ({ signal }) => albumHLSAlbumsTracksHlsKey(albumId, trackId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(albumId && trackId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AlbumHLSAlbumsTracksHlsKeyQueryResult = NonNullable<
  Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>
>;
export type AlbumHLSAlbumsTracksHlsKeyQueryError = unknown;

export function useAlbumHLSAlbumsTracksHlsKey<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
          TError,
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumHLSAlbumsTracksHlsKey<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
          TError,
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumHLSAlbumsTracksHlsKey<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary AES-128 키
 */

export function useAlbumHLSAlbumsTracksHlsKey<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsKey>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAlbumHLSAlbumsTracksHlsKeyQueryOptions(
    albumId,
    trackId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 세그먼트 URL은 CDN, 키 URI는 게이트된 키 엔드포인트로 재작성됨. 공개.
 * @summary HLS 플레이리스트
 */
export const albumHLSAlbumsTracksHlsIndexM3u8 = (
  albumId: number,
  trackId: number,
  signal?: AbortSignal
) => {
  return customInstance<string>({
    url: `/pub/v1/albums/${albumId}/tracks/${trackId}/hls/index.m3u8`,
    method: "GET",
    signal,
  });
};

export const getAlbumHLSAlbumsTracksHlsIndexM3u8QueryKey = (
  albumId?: number,
  trackId?: number
) => {
  return [
    `/pub/v1/albums/${albumId}/tracks/${trackId}/hls/index.m3u8`,
  ] as const;
};

export const getAlbumHLSAlbumsTracksHlsIndexM3u8QueryOptions = <
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAlbumHLSAlbumsTracksHlsIndexM3u8QueryKey(albumId, trackId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>
  > = ({ signal }) =>
    albumHLSAlbumsTracksHlsIndexM3u8(albumId, trackId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(albumId && trackId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AlbumHLSAlbumsTracksHlsIndexM3u8QueryResult = NonNullable<
  Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>
>;
export type AlbumHLSAlbumsTracksHlsIndexM3u8QueryError = unknown;

export function useAlbumHLSAlbumsTracksHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumHLSAlbumsTracksHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
          TError,
          Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAlbumHLSAlbumsTracksHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary HLS 플레이리스트
 */

export function useAlbumHLSAlbumsTracksHlsIndexM3u8<
  TData = Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
  TError = unknown
>(
  albumId: number,
  trackId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof albumHLSAlbumsTracksHlsIndexM3u8>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAlbumHLSAlbumsTracksHlsIndexM3u8QueryOptions(
    albumId,
    trackId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
