/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FeedParams,
  ResultDTODashboardSummaryResponse,
  ResultDTOListFeedItem,
  ResultDTOTimeseriesResponse,
  TimeseriesParams,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 최근 N일 굿즈매출/정기후원/단건후원 스택 시계열(빈 날짜 0 채움). Redis 캐싱(60s).
 * @summary 후원·매출 추이
 */
export const timeseries = (params?: TimeseriesParams, signal?: AbortSignal) => {
  return customInstance<ResultDTOTimeseriesResponse>({
    url: `/v1/dashboard/timeseries`,
    method: "GET",
    params,
    signal,
  });
};

export const getTimeseriesQueryKey = (params?: TimeseriesParams) => {
  return [`/v1/dashboard/timeseries`, ...(params ? [params] : [])] as const;
};

export const getTimeseriesQueryOptions = <
  TData = Awaited<ReturnType<typeof timeseries>>,
  TError = unknown
>(
  params?: TimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof timeseries>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTimeseriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof timeseries>>> = ({
    signal,
  }) => timeseries(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof timeseries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TimeseriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof timeseries>>
>;
export type TimeseriesQueryError = unknown;

export function useTimeseries<
  TData = Awaited<ReturnType<typeof timeseries>>,
  TError = unknown
>(
  params: undefined | TimeseriesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof timeseries>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeseries>>,
          TError,
          Awaited<ReturnType<typeof timeseries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTimeseries<
  TData = Awaited<ReturnType<typeof timeseries>>,
  TError = unknown
>(
  params?: TimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof timeseries>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof timeseries>>,
          TError,
          Awaited<ReturnType<typeof timeseries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTimeseries<
  TData = Awaited<ReturnType<typeof timeseries>>,
  TError = unknown
>(
  params?: TimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof timeseries>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 후원·매출 추이
 */

export function useTimeseries<
  TData = Awaited<ReturnType<typeof timeseries>>,
  TError = unknown
>(
  params?: TimeseriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof timeseries>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTimeseriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 오늘 후원·매출/신규구독/진행중주문/미답변문의/재고경고/활성구독자. Redis 캐싱(60s).
 * @summary KPI 요약
 */
export const summary1 = (signal?: AbortSignal) => {
  return customInstance<ResultDTODashboardSummaryResponse>({
    url: `/v1/dashboard/summary`,
    method: "GET",
    signal,
  });
};

export const getSummary1QueryKey = () => {
  return [`/v1/dashboard/summary`] as const;
};

export const getSummary1QueryOptions = <
  TData = Awaited<ReturnType<typeof summary1>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof summary1>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSummary1QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof summary1>>> = ({
    signal,
  }) => summary1(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof summary1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type Summary1QueryResult = NonNullable<
  Awaited<ReturnType<typeof summary1>>
>;
export type Summary1QueryError = unknown;

export function useSummary1<
  TData = Awaited<ReturnType<typeof summary1>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof summary1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof summary1>>,
          TError,
          Awaited<ReturnType<typeof summary1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSummary1<
  TData = Awaited<ReturnType<typeof summary1>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof summary1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof summary1>>,
          TError,
          Awaited<ReturnType<typeof summary1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSummary1<
  TData = Awaited<ReturnType<typeof summary1>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof summary1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary KPI 요약
 */

export function useSummary1<
  TData = Awaited<ReturnType<typeof summary1>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof summary1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSummary1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 최근 활동 N건(주문·구독·후원 union, 최신순). 캐시 없음.
 * @summary 실시간 활동 피드
 */
export const feed = (params?: FeedParams, signal?: AbortSignal) => {
  return customInstance<ResultDTOListFeedItem>({
    url: `/v1/dashboard/feed`,
    method: "GET",
    params,
    signal,
  });
};

export const getFeedQueryKey = (params?: FeedParams) => {
  return [`/v1/dashboard/feed`, ...(params ? [params] : [])] as const;
};

export const getFeedQueryOptions = <
  TData = Awaited<ReturnType<typeof feed>>,
  TError = unknown
>(
  params?: FeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof feed>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFeedQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof feed>>> = ({
    signal,
  }) => feed(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof feed>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FeedQueryResult = NonNullable<Awaited<ReturnType<typeof feed>>>;
export type FeedQueryError = unknown;

export function useFeed<
  TData = Awaited<ReturnType<typeof feed>>,
  TError = unknown
>(
  params: undefined | FeedParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof feed>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof feed>>,
          TError,
          Awaited<ReturnType<typeof feed>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFeed<
  TData = Awaited<ReturnType<typeof feed>>,
  TError = unknown
>(
  params?: FeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof feed>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof feed>>,
          TError,
          Awaited<ReturnType<typeof feed>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFeed<
  TData = Awaited<ReturnType<typeof feed>>,
  TError = unknown
>(
  params?: FeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof feed>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 실시간 활동 피드
 */

export function useFeed<
  TData = Awaited<ReturnType<typeof feed>>,
  TError = unknown
>(
  params?: FeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof feed>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFeedQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
