/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FavoriteAddRequest,
  HistoryRecordRequest,
  ResultDTOListFavoriteItem,
  ResultDTOListMyInquiryItem,
  ResultDTOListMyReviewItem,
  ResultDTOListPurchasedAlbumItem,
  ResultDTOListWatchHistoryItem,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 로그인 회원의 최근 시청기록을 콘텐츠 정보와 함께 최신순으로 반환한다.
 * @summary 시청기록
 */
export const memberMeMeHistory = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListWatchHistoryItem>({
    url: `/pub/v1/me/history`,
    method: "GET",
    signal,
  });
};

export const getMemberMeMeHistoryQueryKey = () => {
  return [`/pub/v1/me/history`] as const;
};

export const getMemberMeMeHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof memberMeMeHistory>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberMeMeHistory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberMeMeHistoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberMeMeHistory>>
  > = ({ signal }) => memberMeMeHistory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberMeMeHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberMeMeHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeHistory>>
>;
export type MemberMeMeHistoryQueryError = unknown;

export function useMemberMeMeHistory<
  TData = Awaited<ReturnType<typeof memberMeMeHistory>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeHistory>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeHistory<
  TData = Awaited<ReturnType<typeof memberMeMeHistory>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeHistory>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeHistory<
  TData = Awaited<ReturnType<typeof memberMeMeHistory>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 시청기록
 */

export function useMemberMeMeHistory<
  TData = Awaited<ReturnType<typeof memberMeMeHistory>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberMeMeHistoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 콘텐츠 시청 이벤트 1건을 기록한다(멱등 아님, best-effort).
 * @summary 시청기록 적재
 */
export const memberMeMeHistoryCreate = (
  historyRecordRequest: HistoryRecordRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/me/history`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: historyRecordRequest,
    signal,
  });
};

export const getMemberMeMeHistoryCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberMeMeHistoryCreate>>,
    TError,
    { data: HistoryRecordRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberMeMeHistoryCreate>>,
  TError,
  { data: HistoryRecordRequest },
  TContext
> => {
  const mutationKey = ["memberMeMeHistoryCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberMeMeHistoryCreate>>,
    { data: HistoryRecordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberMeMeHistoryCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberMeMeHistoryCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeHistoryCreate>>
>;
export type MemberMeMeHistoryCreateMutationBody = HistoryRecordRequest;
export type MemberMeMeHistoryCreateMutationError = unknown;

/**
 * @summary 시청기록 적재
 */
export const useMemberMeMeHistoryCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberMeMeHistoryCreate>>,
      TError,
      { data: HistoryRecordRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberMeMeHistoryCreate>>,
  TError,
  { data: HistoryRecordRequest },
  TContext
> => {
  const mutationOptions = getMemberMeMeHistoryCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 로그인 회원의 재생목록 찜을 트랙/앨범 정보와 함께 반환한다.
 * @summary 찜 목록
 */
export const memberMeMeFavorites = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListFavoriteItem>({
    url: `/pub/v1/me/favorites`,
    method: "GET",
    signal,
  });
};

export const getMemberMeMeFavoritesQueryKey = () => {
  return [`/pub/v1/me/favorites`] as const;
};

export const getMemberMeMeFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof memberMeMeFavorites>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberMeMeFavorites>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberMeMeFavoritesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberMeMeFavorites>>
  > = ({ signal }) => memberMeMeFavorites(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberMeMeFavorites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberMeMeFavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeFavorites>>
>;
export type MemberMeMeFavoritesQueryError = unknown;

export function useMemberMeMeFavorites<
  TData = Awaited<ReturnType<typeof memberMeMeFavorites>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeFavorites>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeFavorites>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeFavorites>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeFavorites<
  TData = Awaited<ReturnType<typeof memberMeMeFavorites>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeFavorites>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeFavorites>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeFavorites>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeFavorites<
  TData = Awaited<ReturnType<typeof memberMeMeFavorites>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeFavorites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 찜 목록
 */

export function useMemberMeMeFavorites<
  TData = Awaited<ReturnType<typeof memberMeMeFavorites>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeFavorites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberMeMeFavoritesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 트랙을 재생목록 찜에 추가한다(이미 있으면 무시, 멱등).
 * @summary 찜 추가
 */
export const memberMeMeFavoritesCreate = (
  favoriteAddRequest: FavoriteAddRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/me/favorites`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: favoriteAddRequest,
    signal,
  });
};

export const getMemberMeMeFavoritesCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>,
    TError,
    { data: FavoriteAddRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>,
  TError,
  { data: FavoriteAddRequest },
  TContext
> => {
  const mutationKey = ["memberMeMeFavoritesCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>,
    { data: FavoriteAddRequest }
  > = (props) => {
    const { data } = props ?? {};

    return memberMeMeFavoritesCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberMeMeFavoritesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>
>;
export type MemberMeMeFavoritesCreateMutationBody = FavoriteAddRequest;
export type MemberMeMeFavoritesCreateMutationError = unknown;

/**
 * @summary 찜 추가
 */
export const useMemberMeMeFavoritesCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>,
      TError,
      { data: FavoriteAddRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberMeMeFavoritesCreate>>,
  TError,
  { data: FavoriteAddRequest },
  TContext
> => {
  const mutationOptions = getMemberMeMeFavoritesCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 로그인 회원이 작성한 상품 후기 목록을 반환한다.
 * @summary 내 후기
 */
export const memberMeMeReviews = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListMyReviewItem>({
    url: `/pub/v1/me/reviews`,
    method: "GET",
    signal,
  });
};

export const getMemberMeMeReviewsQueryKey = () => {
  return [`/pub/v1/me/reviews`] as const;
};

export const getMemberMeMeReviewsQueryOptions = <
  TData = Awaited<ReturnType<typeof memberMeMeReviews>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberMeMeReviews>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberMeMeReviewsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberMeMeReviews>>
  > = ({ signal }) => memberMeMeReviews(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberMeMeReviews>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberMeMeReviewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeReviews>>
>;
export type MemberMeMeReviewsQueryError = unknown;

export function useMemberMeMeReviews<
  TData = Awaited<ReturnType<typeof memberMeMeReviews>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeReviews>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeReviews>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeReviews>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeReviews<
  TData = Awaited<ReturnType<typeof memberMeMeReviews>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeReviews>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeReviews>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeReviews>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeReviews<
  TData = Awaited<ReturnType<typeof memberMeMeReviews>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeReviews>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 후기
 */

export function useMemberMeMeReviews<
  TData = Awaited<ReturnType<typeof memberMeMeReviews>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeReviews>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberMeMeReviewsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 로그인 회원이 작성한 상품 문의 목록을 반환한다.
 * @summary 내 문의
 */
export const memberMeMeInquiries = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListMyInquiryItem>({
    url: `/pub/v1/me/inquiries`,
    method: "GET",
    signal,
  });
};

export const getMemberMeMeInquiriesQueryKey = () => {
  return [`/pub/v1/me/inquiries`] as const;
};

export const getMemberMeMeInquiriesQueryOptions = <
  TData = Awaited<ReturnType<typeof memberMeMeInquiries>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof memberMeMeInquiries>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberMeMeInquiriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberMeMeInquiries>>
  > = ({ signal }) => memberMeMeInquiries(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberMeMeInquiries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberMeMeInquiriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeInquiries>>
>;
export type MemberMeMeInquiriesQueryError = unknown;

export function useMemberMeMeInquiries<
  TData = Awaited<ReturnType<typeof memberMeMeInquiries>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeInquiries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeInquiries>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeInquiries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeInquiries<
  TData = Awaited<ReturnType<typeof memberMeMeInquiries>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeInquiries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeInquiries>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeInquiries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeInquiries<
  TData = Awaited<ReturnType<typeof memberMeMeInquiries>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeInquiries>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 문의
 */

export function useMemberMeMeInquiries<
  TData = Awaited<ReturnType<typeof memberMeMeInquiries>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeInquiries>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberMeMeInquiriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 로그인 회원의 결제완료 주문에 포함된 앨범 목록(중복 제거)을 반환한다.
 * @summary 구매 음반
 */
export const memberMeMeAlbums = (signal?: AbortSignal) => {
  return customInstance<ResultDTOListPurchasedAlbumItem>({
    url: `/pub/v1/me/albums`,
    method: "GET",
    signal,
  });
};

export const getMemberMeMeAlbumsQueryKey = () => {
  return [`/pub/v1/me/albums`] as const;
};

export const getMemberMeMeAlbumsQueryOptions = <
  TData = Awaited<ReturnType<typeof memberMeMeAlbums>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof memberMeMeAlbums>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMemberMeMeAlbumsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof memberMeMeAlbums>>
  > = ({ signal }) => memberMeMeAlbums(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof memberMeMeAlbums>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MemberMeMeAlbumsQueryResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeAlbums>>
>;
export type MemberMeMeAlbumsQueryError = unknown;

export function useMemberMeMeAlbums<
  TData = Awaited<ReturnType<typeof memberMeMeAlbums>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeAlbums>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeAlbums>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeAlbums>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeAlbums<
  TData = Awaited<ReturnType<typeof memberMeMeAlbums>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeAlbums>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof memberMeMeAlbums>>,
          TError,
          Awaited<ReturnType<typeof memberMeMeAlbums>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMemberMeMeAlbums<
  TData = Awaited<ReturnType<typeof memberMeMeAlbums>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeAlbums>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구매 음반
 */

export function useMemberMeMeAlbums<
  TData = Awaited<ReturnType<typeof memberMeMeAlbums>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof memberMeMeAlbums>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMemberMeMeAlbumsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 트랙을 재생목록 찜에서 제거한다.
 * @summary 찜 해제
 */
export const memberMeMeFavoritesDelete = (trackId: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/pub/v1/me/favorites/${trackId}`,
    method: "DELETE",
  });
};

export const getMemberMeMeFavoritesDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>,
    TError,
    { trackId: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>,
  TError,
  { trackId: number },
  TContext
> => {
  const mutationKey = ["memberMeMeFavoritesDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>,
    { trackId: number }
  > = (props) => {
    const { trackId } = props ?? {};

    return memberMeMeFavoritesDelete(trackId);
  };

  return { mutationFn, ...mutationOptions };
};

export type MemberMeMeFavoritesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>
>;

export type MemberMeMeFavoritesDeleteMutationError = unknown;

/**
 * @summary 찜 해제
 */
export const useMemberMeMeFavoritesDelete = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>,
      TError,
      { trackId: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof memberMeMeFavoritesDelete>>,
  TError,
  { trackId: number },
  TContext
> => {
  const mutationOptions = getMemberMeMeFavoritesDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
