/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CommunityPostSaveRequest,
  CommunityPostSearchRequest,
  ResultDTOCommunityPostDto,
  ResultDTOListCommunityPostDto,
  ResultDTOVoid,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 게시글 상세
 */
export const postCommunityPostDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOCommunityPostDto>({
    url: `/v1/community-post/${id}`,
    method: "GET",
    signal,
  });
};

export const getPostCommunityPostDetailQueryKey = (id?: number) => {
  return [`/v1/community-post/${id}`] as const;
};

export const getPostCommunityPostDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof postCommunityPostDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postCommunityPostDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPostCommunityPostDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof postCommunityPostDetail>>
  > = ({ signal }) => postCommunityPostDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postCommunityPostDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostCommunityPostDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof postCommunityPostDetail>>
>;
export type PostCommunityPostDetailQueryError = unknown;

export function usePostCommunityPostDetail<
  TData = Awaited<ReturnType<typeof postCommunityPostDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postCommunityPostDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCommunityPostDetail>>,
          TError,
          Awaited<ReturnType<typeof postCommunityPostDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostCommunityPostDetail<
  TData = Awaited<ReturnType<typeof postCommunityPostDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postCommunityPostDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCommunityPostDetail>>,
          TError,
          Awaited<ReturnType<typeof postCommunityPostDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostCommunityPostDetail<
  TData = Awaited<ReturnType<typeof postCommunityPostDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postCommunityPostDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 게시글 상세
 */

export function usePostCommunityPostDetail<
  TData = Awaited<ReturnType<typeof postCommunityPostDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof postCommunityPostDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostCommunityPostDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 기존 게시글의 작성 항목을 수정한다(조회수/추천수 유지).
 * @summary 게시글 수정
 */
export const postCommunityPostUpdate = (
  id: number,
  communityPostSaveRequest: CommunityPostSaveRequest
) => {
  return customInstance<ResultDTOCommunityPostDto>({
    url: `/v1/community-post/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: communityPostSaveRequest,
  });
};

export const getPostCommunityPostUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCommunityPostUpdate>>,
    TError,
    { id: number; data: CommunityPostSaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCommunityPostUpdate>>,
  TError,
  { id: number; data: CommunityPostSaveRequest },
  TContext
> => {
  const mutationKey = ["postCommunityPostUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCommunityPostUpdate>>,
    { id: number; data: CommunityPostSaveRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postCommunityPostUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommunityPostUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCommunityPostUpdate>>
>;
export type PostCommunityPostUpdateMutationBody = CommunityPostSaveRequest;
export type PostCommunityPostUpdateMutationError = unknown;

/**
 * @summary 게시글 수정
 */
export const usePostCommunityPostUpdate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCommunityPostUpdate>>,
      TError,
      { id: number; data: CommunityPostSaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postCommunityPostUpdate>>,
  TError,
  { id: number; data: CommunityPostSaveRequest },
  TContext
> => {
  const mutationOptions = getPostCommunityPostUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 게시글 삭제
 */
export const postCommunityPostDelete = (id: number) => {
  return customInstance<ResultDTOVoid>({
    url: `/v1/community-post/${id}`,
    method: "DELETE",
  });
};

export const getPostCommunityPostDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCommunityPostDelete>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCommunityPostDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["postCommunityPostDelete"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCommunityPostDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return postCommunityPostDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommunityPostDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCommunityPostDelete>>
>;

export type PostCommunityPostDeleteMutationError = unknown;

/**
 * @summary 게시글 삭제
 */
export const usePostCommunityPostDelete = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCommunityPostDelete>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postCommunityPostDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getPostCommunityPostDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 글 관리 작성 화면에서 새 게시글을 등록한다.
 * @summary 게시글 등록
 */
export const postCommunityPostCreate = (
  communityPostSaveRequest: CommunityPostSaveRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOCommunityPostDto>({
    url: `/v1/community-post`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: communityPostSaveRequest,
    signal,
  });
};

export const getPostCommunityPostCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCommunityPostCreate>>,
    TError,
    { data: CommunityPostSaveRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCommunityPostCreate>>,
  TError,
  { data: CommunityPostSaveRequest },
  TContext
> => {
  const mutationKey = ["postCommunityPostCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCommunityPostCreate>>,
    { data: CommunityPostSaveRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postCommunityPostCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommunityPostCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCommunityPostCreate>>
>;
export type PostCommunityPostCreateMutationBody = CommunityPostSaveRequest;
export type PostCommunityPostCreateMutationError = unknown;

/**
 * @summary 게시글 등록
 */
export const usePostCommunityPostCreate = <
  TError = unknown,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCommunityPostCreate>>,
      TError,
      { data: CommunityPostSaveRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postCommunityPostCreate>>,
  TError,
  { data: CommunityPostSaveRequest },
  TContext
> => {
  const mutationOptions = getPostCommunityPostCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 게시판/카테고리/검색어 필터, 최신순 전체 목록.
 * @summary 게시글 목록
 */
export const postCommunityPostList = (
  communityPostSearchRequest: CommunityPostSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOListCommunityPostDto>({
    url: `/v1/community-post/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: communityPostSearchRequest,
    signal,
  });
};

export const getPostCommunityPostListMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCommunityPostList>>,
    TError,
    { data: CommunityPostSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCommunityPostList>>,
  TError,
  { data: CommunityPostSearchRequest },
  TContext
> => {
  const mutationKey = ["postCommunityPostList"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCommunityPostList>>,
    { data: CommunityPostSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postCommunityPostList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommunityPostListMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCommunityPostList>>
>;
export type PostCommunityPostListMutationBody = CommunityPostSearchRequest;
export type PostCommunityPostListMutationError = unknown;

/**
 * @summary 게시글 목록
 */
export const usePostCommunityPostList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCommunityPostList>>,
      TError,
      { data: CommunityPostSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postCommunityPostList>>,
  TError,
  { data: CommunityPostSearchRequest },
  TContext
> => {
  const mutationOptions = getPostCommunityPostListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
