/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ContentsParams,
  PostsParams,
  ResultDTOContentDetail,
  ResultDTOPostDetail,
  ResultDTOPublicHomeResponse,
  ResultDTOResInfinityListContentListItem,
  ResultDTOResInfinityListPostListItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * PUBLISHED 게시글 목록(검색·페이지네이션).
 * @summary 공개 게시글 목록
 */
export const posts = (params?: PostsParams, signal?: AbortSignal) => {
  return customInstance<ResultDTOResInfinityListPostListItem>({
    url: `/pub/v1/posts`,
    method: "GET",
    params,
    signal,
  });
};

export const getPostsQueryKey = (params?: PostsParams) => {
  return [`/pub/v1/posts`, ...(params ? [params] : [])] as const;
};

export const getPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof posts>>,
  TError = unknown
>(
  params?: PostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof posts>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof posts>>> = ({
    signal,
  }) => posts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof posts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostsQueryResult = NonNullable<Awaited<ReturnType<typeof posts>>>;
export type PostsQueryError = unknown;

export function usePosts<
  TData = Awaited<ReturnType<typeof posts>>,
  TError = unknown
>(
  params: undefined | PostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof posts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof posts>>,
          TError,
          Awaited<ReturnType<typeof posts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePosts<
  TData = Awaited<ReturnType<typeof posts>>,
  TError = unknown
>(
  params?: PostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof posts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof posts>>,
          TError,
          Awaited<ReturnType<typeof posts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePosts<
  TData = Awaited<ReturnType<typeof posts>>,
  TError = unknown
>(
  params?: PostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof posts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 목록
 */

export function usePosts<
  TData = Awaited<ReturnType<typeof posts>>,
  TError = unknown
>(
  params?: PostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof posts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 공개 게시글 상세
 */
export const postDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOPostDetail>({
    url: `/pub/v1/posts/${id}`,
    method: "GET",
    signal,
  });
};

export const getPostDetailQueryKey = (id?: number) => {
  return [`/pub/v1/posts/${id}`] as const;
};

export const getPostDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof postDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPostDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof postDetail>>> = ({
    signal,
  }) => postDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof postDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof postDetail>>
>;
export type PostDetailQueryError = unknown;

export function usePostDetail<
  TData = Awaited<ReturnType<typeof postDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postDetail>>,
          TError,
          Awaited<ReturnType<typeof postDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostDetail<
  TData = Awaited<ReturnType<typeof postDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postDetail>>,
          TError,
          Awaited<ReturnType<typeof postDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePostDetail<
  TData = Awaited<ReturnType<typeof postDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 게시글 상세
 */

export function usePostDetail<
  TData = Awaited<ReturnType<typeof postDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof postDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPostDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * 최신 영상/음악/게시글을 한 번에 반환.
 * @summary 홈 묶음
 */
export const home = (signal?: AbortSignal) => {
  return customInstance<ResultDTOPublicHomeResponse>({
    url: `/pub/v1/home`,
    method: "GET",
    signal,
  });
};

export const getHomeQueryKey = () => {
  return [`/pub/v1/home`] as const;
};

export const getHomeQueryOptions = <
  TData = Awaited<ReturnType<typeof home>>,
  TError = unknown
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHomeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof home>>> = ({
    signal,
  }) => home(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof home>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HomeQueryResult = NonNullable<Awaited<ReturnType<typeof home>>>;
export type HomeQueryError = unknown;

export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = unknown
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof home>>,
          TError,
          Awaited<ReturnType<typeof home>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof home>>,
          TError,
          Awaited<ReturnType<typeof home>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 홈 묶음
 */

export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = unknown
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHomeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED 영상/음악 목록(검색·페이지네이션).
 * @summary 공개 콘텐츠 목록
 */
export const contents = (params?: ContentsParams, signal?: AbortSignal) => {
  return customInstance<ResultDTOResInfinityListContentListItem>({
    url: `/pub/v1/contents`,
    method: "GET",
    params,
    signal,
  });
};

export const getContentsQueryKey = (params?: ContentsParams) => {
  return [`/pub/v1/contents`, ...(params ? [params] : [])] as const;
};

export const getContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof contents>>,
  TError = unknown
>(
  params?: ContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contents>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contents>>> = ({
    signal,
  }) => contents(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof contents>>
>;
export type ContentsQueryError = unknown;

export function useContents<
  TData = Awaited<ReturnType<typeof contents>>,
  TError = unknown
>(
  params: undefined | ContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contents>>,
          TError,
          Awaited<ReturnType<typeof contents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContents<
  TData = Awaited<ReturnType<typeof contents>>,
  TError = unknown
>(
  params?: ContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contents>>,
          TError,
          Awaited<ReturnType<typeof contents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContents<
  TData = Awaited<ReturnType<typeof contents>>,
  TError = unknown
>(
  params?: ContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 목록
 */

export function useContents<
  TData = Awaited<ReturnType<typeof contents>>,
  TError = unknown
>(
  params?: ContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contents>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * PUBLISHED만 반환하며 조회수를 1 증가시킨다.
 * @summary 공개 콘텐츠 상세
 */
export const contentDetail = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOContentDetail>({
    url: `/pub/v1/contents/${id}`,
    method: "GET",
    signal,
  });
};

export const getContentDetailQueryKey = (id?: number) => {
  return [`/pub/v1/contents/${id}`] as const;
};

export const getContentDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentDetail>>> = ({
    signal,
  }) => contentDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof contentDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentDetail>>
>;
export type ContentDetailQueryError = unknown;

export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentDetail>>,
          TError,
          Awaited<ReturnType<typeof contentDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentDetail>>,
          TError,
          Awaited<ReturnType<typeof contentDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 콘텐츠 상세
 */

export function useContentDetail<
  TData = Awaited<ReturnType<typeof contentDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentDetail>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContentDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
