/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatSendRequest,
  ResultDTOChatReplyDto,
  ResultDTOListChatHistoryItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 최신 메시지 한 건만 룰 기반으로 분류해 응답한다(이전 대화 맥락 미반영). USER/BOT 턴은 세션에 저장된다. 과도한 요청은 429.
 * @summary 챗봇 메시지 전송
 */
export const chatSendCreate = (
  chatSendRequest: ChatSendRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOChatReplyDto>({
    url: `/v1/chat/send`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: chatSendRequest,
    signal,
  });
};

export const getChatSendCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatSendCreate>>,
    TError,
    { data: ChatSendRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatSendCreate>>,
  TError,
  { data: ChatSendRequest },
  TContext
> => {
  const mutationKey = ["chatSendCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatSendCreate>>,
    { data: ChatSendRequest }
  > = (props) => {
    const { data } = props ?? {};

    return chatSendCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatSendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatSendCreate>>
>;
export type ChatSendCreateMutationBody = ChatSendRequest;
export type ChatSendCreateMutationError = unknown;

/**
 * @summary 챗봇 메시지 전송
 */
export const useChatSendCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatSendCreate>>,
      TError,
      { data: ChatSendRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chatSendCreate>>,
  TError,
  { data: ChatSendRequest },
  TContext
> => {
  const mutationOptions = getChatSendCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 세션키 기준 전체 대화 이력(오래된 순).
 * @summary 챗봇 대화 이력
 */
export const chatHistory = (sessionKey: string, signal?: AbortSignal) => {
  return customInstance<ResultDTOListChatHistoryItem>({
    url: `/v1/chat/${sessionKey}/history`,
    method: "GET",
    signal,
  });
};

export const getChatHistoryQueryKey = (sessionKey?: string) => {
  return [`/v1/chat/${sessionKey}/history`] as const;
};

export const getChatHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof chatHistory>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChatHistoryQueryKey(sessionKey);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof chatHistory>>> = ({
    signal,
  }) => chatHistory(sessionKey, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!sessionKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof chatHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatHistory>>
>;
export type ChatHistoryQueryError = unknown;

export function useChatHistory<
  TData = Awaited<ReturnType<typeof chatHistory>>,
  TError = unknown
>(
  sessionKey: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatHistory>>,
          TError,
          Awaited<ReturnType<typeof chatHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatHistory<
  TData = Awaited<ReturnType<typeof chatHistory>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatHistory>>,
          TError,
          Awaited<ReturnType<typeof chatHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatHistory<
  TData = Awaited<ReturnType<typeof chatHistory>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 챗봇 대화 이력
 */

export function useChatHistory<
  TData = Awaited<ReturnType<typeof chatHistory>>,
  TError = unknown
>(
  sessionKey: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof chatHistory>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatHistoryQueryOptions(sessionKey, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
