/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResultDTOResInfinityListSecurityEventItem,
  SecurityEventSecurityEventsParams,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * 인증 실패/접근 거부/보안 알림을 최신순으로 페이지네이션 조회한다.
 * @summary 보안 이벤트 목록
 */
export const securityEventSecurityEvents = (
  params?: SecurityEventSecurityEventsParams,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListSecurityEventItem>({
    url: `/v1/security-events`,
    method: "GET",
    params,
    signal,
  });
};

export const getSecurityEventSecurityEventsQueryKey = (
  params?: SecurityEventSecurityEventsParams
) => {
  return [`/v1/security-events`, ...(params ? [params] : [])] as const;
};

export const getSecurityEventSecurityEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof securityEventSecurityEvents>>,
  TError = unknown
>(
  params?: SecurityEventSecurityEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof securityEventSecurityEvents>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSecurityEventSecurityEventsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof securityEventSecurityEvents>>
  > = ({ signal }) => securityEventSecurityEvents(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof securityEventSecurityEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SecurityEventSecurityEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof securityEventSecurityEvents>>
>;
export type SecurityEventSecurityEventsQueryError = unknown;

export function useSecurityEventSecurityEvents<
  TData = Awaited<ReturnType<typeof securityEventSecurityEvents>>,
  TError = unknown
>(
  params: undefined | SecurityEventSecurityEventsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof securityEventSecurityEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof securityEventSecurityEvents>>,
          TError,
          Awaited<ReturnType<typeof securityEventSecurityEvents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSecurityEventSecurityEvents<
  TData = Awaited<ReturnType<typeof securityEventSecurityEvents>>,
  TError = unknown
>(
  params?: SecurityEventSecurityEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof securityEventSecurityEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof securityEventSecurityEvents>>,
          TError,
          Awaited<ReturnType<typeof securityEventSecurityEvents>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSecurityEventSecurityEvents<
  TData = Awaited<ReturnType<typeof securityEventSecurityEvents>>,
  TError = unknown
>(
  params?: SecurityEventSecurityEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof securityEventSecurityEvents>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 보안 이벤트 목록
 */

export function useSecurityEventSecurityEvents<
  TData = Awaited<ReturnType<typeof securityEventSecurityEvents>>,
  TError = unknown
>(
  params?: SecurityEventSecurityEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof securityEventSecurityEvents>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSecurityEventSecurityEventsQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
