/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * StreamHub Admin API
 * 관리자 내부 API (a production service 관리자 API 포트폴리오 클론)
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  IdListRequest,
  MemberSearchRequest,
  MemberUpdateRequest,
  ResultDTOInteger,
  ResultDTOMemberDetail,
  ResultDTOResInfinityListMemberListItem,
} from "../streamHubAdminAPI.schemas";

import { customInstance } from "../../custom-instance";

/**
 * @summary 회원 상세
 */
export const detail1 = (id: number, signal?: AbortSignal) => {
  return customInstance<ResultDTOMemberDetail>({
    url: `/v1/member/${id}`,
    method: "GET",
    signal,
  });
};

export const getDetail1QueryKey = (id?: number) => {
  return [`/v1/member/${id}`] as const;
};

export const getDetail1QueryOptions = <
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDetail1QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof detail1>>> = ({
    signal,
  }) => detail1(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Detail1QueryResult = NonNullable<
  Awaited<ReturnType<typeof detail1>>
>;
export type Detail1QueryError = unknown;

export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail1>>,
          TError,
          Awaited<ReturnType<typeof detail1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail1>>,
          TError,
          Awaited<ReturnType<typeof detail1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원 상세
 */

export function useDetail1<
  TData = Awaited<ReturnType<typeof detail1>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof detail1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDetail1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 회원 수정
 */
export const update1 = (
  id: number,
  memberUpdateRequest: MemberUpdateRequest
) => {
  return customInstance<ResultDTOMemberDetail>({
    url: `/v1/member/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: memberUpdateRequest,
  });
};

export const getUpdate1MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update1>>,
    TError,
    { id: number; data: MemberUpdateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: number; data: MemberUpdateRequest },
  TContext
> => {
  const mutationKey = ["update1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update1>>,
    { id: number; data: MemberUpdateRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return update1(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update1MutationResult = NonNullable<
  Awaited<ReturnType<typeof update1>>
>;
export type Update1MutationBody = MemberUpdateRequest;
export type Update1MutationError = unknown;

/**
 * @summary 회원 수정
 */
export const useUpdate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update1>>,
      TError,
      { id: number; data: MemberUpdateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { id: number; data: MemberUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdate1MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 검색/필터/페이지네이션된 회원 목록을 반환한다.
 * @summary 회원 목록
 */
export const list3 = (
  memberSearchRequest: MemberSearchRequest,
  signal?: AbortSignal
) => {
  return customInstance<ResultDTOResInfinityListMemberListItem>({
    url: `/v1/member/list`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: memberSearchRequest,
    signal,
  });
};

export const getList3MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof list3>>,
    TError,
    { data: MemberSearchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof list3>>,
  TError,
  { data: MemberSearchRequest },
  TContext
> => {
  const mutationKey = ["list3"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof list3>>,
    { data: MemberSearchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return list3(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type List3MutationResult = NonNullable<
  Awaited<ReturnType<typeof list3>>
>;
export type List3MutationBody = MemberSearchRequest;
export type List3MutationError = unknown;

/**
 * @summary 회원 목록
 */
export const useList3 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof list3>>,
      TError,
      { data: MemberSearchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof list3>>,
  TError,
  { data: MemberSearchRequest },
  TContext
> => {
  const mutationOptions = getList3MutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 회원을 INACTIVE로 변경한다.
 * @summary 회원 일괄 거부
 */
export const deny = (idListRequest: IdListRequest, signal?: AbortSignal) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/member/deny`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: idListRequest,
    signal,
  });
};

export const getDenyMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deny>>,
    TError,
    { data: IdListRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deny>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationKey = ["deny"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deny>>,
    { data: IdListRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deny(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DenyMutationResult = NonNullable<Awaited<ReturnType<typeof deny>>>;
export type DenyMutationBody = IdListRequest;
export type DenyMutationError = unknown;

/**
 * @summary 회원 일괄 거부
 */
export const useDeny = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deny>>,
      TError,
      { data: IdListRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deny>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationOptions = getDenyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * 선택한 회원을 CONFIRMED로 변경한다.
 * @summary 회원 일괄 승인
 */
export const approve = (idListRequest: IdListRequest, signal?: AbortSignal) => {
  return customInstance<ResultDTOInteger>({
    url: `/v1/member/approve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: idListRequest,
    signal,
  });
};

export const getApproveMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approve>>,
    TError,
    { data: IdListRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approve>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationKey = ["approve"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approve>>,
    { data: IdListRequest }
  > = (props) => {
    const { data } = props ?? {};

    return approve(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof approve>>
>;
export type ApproveMutationBody = IdListRequest;
export type ApproveMutationError = unknown;

/**
 * @summary 회원 일괄 승인
 */
export const useApprove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approve>>,
      TError,
      { data: IdListRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approve>>,
  TError,
  { data: IdListRequest },
  TContext
> => {
  const mutationOptions = getApproveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
